#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Earwig_Augusta

#include "Basic.hpp"

#include "AB_Earwig_Augusta_classes.hpp"
#include "AB_Earwig_Augusta_parameters.hpp"


SDK_NAMESPACE_START

// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAB_Earwig_Augusta_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "AnimGraph");

	Params::AB_Earwig_Augusta_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.BeginPlayCommon
// (BlueprintCallable, BlueprintEvent)

void UAB_Earwig_Augusta_C::BeginPlayCommon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "BeginPlayCommon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.BeginPlayIK
// (BlueprintCallable, BlueprintEvent)

void UAB_Earwig_Augusta_C::BeginPlayIK()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "BeginPlayIK");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.BeginPlayMounts
// (BlueprintCallable, BlueprintEvent)

void UAB_Earwig_Augusta_C::BeginPlayMounts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "BeginPlayMounts");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.BlueprintBeginPlay
// (Event, Public, BlueprintEvent)

void UAB_Earwig_Augusta_C::BlueprintBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "BlueprintBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAB_Earwig_Augusta_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "BlueprintUpdateAnimation");

	Params::AB_Earwig_Augusta_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ApplyAdditive_397EB30D427BCE8B43B6E4823F425720
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ApplyAdditive_397EB30D427BCE8B43B6E4823F425720()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ApplyAdditive_397EB30D427BCE8B43B6E4823F425720");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendListByBool_6312EA70432FC8120EFF7E898E1A0C01
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendListByBool_6312EA70432FC8120EFF7E898E1A0C01()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendListByBool_6312EA70432FC8120EFF7E898E1A0C01");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendSpacePlayer_40DF3DA64786325D4470029D777FE2FF
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendSpacePlayer_40DF3DA64786325D4470029D777FE2FF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendSpacePlayer_40DF3DA64786325D4470029D777FE2FF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendSpacePlayer_F935722D42B0B147CADF848293B7CCFD
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendSpacePlayer_F935722D42B0B147CADF848293B7CCFD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_BlendSpacePlayer_F935722D42B0B147CADF848293B7CCFD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ControlRig_879DFEBB47C422AB4C34ACA687BD0F36
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ControlRig_879DFEBB47C422AB4C34ACA687BD0F36()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ControlRig_879DFEBB47C422AB4C34ACA687BD0F36");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ControlRig_AC4242284E97AB06A7FC02B5DCFA30DE
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ControlRig_AC4242284E97AB06A7FC02B5DCFA30DE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ControlRig_AC4242284E97AB06A7FC02B5DCFA30DE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ModifyBone_072E5A3342C21CC0F9DCB6B14CE19A44
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ModifyBone_072E5A3342C21CC0F9DCB6B14CE19A44()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_ModifyBone_072E5A3342C21CC0F9DCB6B14CE19A44");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequenceEvaluator_58C4802046BFA85B691056B8ED0CF57A
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequenceEvaluator_58C4802046BFA85B691056B8ED0CF57A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequenceEvaluator_58C4802046BFA85B691056B8ED0CF57A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequenceEvaluator_8DF7D4D140896BECC75A71AC4DEF0AE6
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequenceEvaluator_8DF7D4D140896BECC75A71AC4DEF0AE6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequenceEvaluator_8DF7D4D140896BECC75A71AC4DEF0AE6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_3AA4EF584848ECCA0417EC895A7AA6FD
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_3AA4EF584848ECCA0417EC895A7AA6FD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_3AA4EF584848ECCA0417EC895A7AA6FD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_6CA177C34F0E35ABF294E0A07AA389C0
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_6CA177C34F0E35ABF294E0A07AA389C0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_6CA177C34F0E35ABF294E0A07AA389C0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_99184C784B431A8E15D55898ED7159D1
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_99184C784B431A8E15D55898ED7159D1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_99184C784B431A8E15D55898ED7159D1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_BC3A3C374FEBA24CFF682993CA612410
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_BC3A3C374FEBA24CFF682993CA612410()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_SequencePlayer_BC3A3C374FEBA24CFF682993CA612410");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_4248FD024C63724206B9239909C25F4F
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_4248FD024C63724206B9239909C25F4F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_4248FD024C63724206B9239909C25F4F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_495F2B5C42A3B0CACDA796A05CA27CDD
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_495F2B5C42A3B0CACDA796A05CA27CDD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_495F2B5C42A3B0CACDA796A05CA27CDD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_59383EAD440A0AFC005FCABCFC828DFD
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_59383EAD440A0AFC005FCABCFC828DFD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_59383EAD440A0AFC005FCABCFC828DFD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_6BEC2E1940DEEE3BD64B1CB4AF3BF0FB
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_6BEC2E1940DEEE3BD64B1CB4AF3BF0FB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_6BEC2E1940DEEE3BD64B1CB4AF3BF0FB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_8A660EAD440684E315897DABD9F44D29
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_8A660EAD440684E315897DABD9F44D29()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_8A660EAD440684E315897DABD9F44D29");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_8FD0E03241A0976BCB43D48ADA8AA1CF
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_8FD0E03241A0976BCB43D48ADA8AA1CF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_8FD0E03241A0976BCB43D48ADA8AA1CF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_F6544FBE42FC35482D6C4289FF0B71E2
// (BlueprintEvent)

void UAB_Earwig_Augusta_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_F6544FBE42FC35482D6C4289FF0B71E2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Earwig_Augusta_AnimGraphNode_TransitionResult_F6544FBE42FC35482D6C4289FF0B71E2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.ExecuteUbergraph_AB_Earwig_Augusta
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAB_Earwig_Augusta_C::ExecuteUbergraph_AB_Earwig_Augusta(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "ExecuteUbergraph_AB_Earwig_Augusta");

	Params::AB_Earwig_Augusta_C_ExecuteUbergraph_AB_Earwig_Augusta Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.OnDamageTarget_Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DamagedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FDamageInfo&               DamageInfo                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAB_Earwig_Augusta_C::OnDamageTarget_Event(class AActor* DamagedActor, const struct FDamageInfo& DamageInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "OnDamageTarget_Event");

	Params::AB_Earwig_Augusta_C_OnDamageTarget_Event Parms{};

	Parms.DamagedActor = DamagedActor;
	Parms.DamageInfo = std::move(DamageInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.OnUpdate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UAB_Earwig_Augusta_C::OnUpdate(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "OnUpdate");

	Params::AB_Earwig_Augusta_C_OnUpdate Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.ResetAdditiveHitstop
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UAB_Earwig_Augusta_C::ResetAdditiveHitstop(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "ResetAdditiveHitstop");

	Params::AB_Earwig_Augusta_C_ResetAdditiveHitstop Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.SaveHitStopPose
// (BlueprintCallable, BlueprintEvent)

void UAB_Earwig_Augusta_C::SaveHitStopPose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "SaveHitStopPose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.SwitchBool
// (BlueprintCallable, BlueprintEvent)

void UAB_Earwig_Augusta_C::SwitchBool()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "SwitchBool");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.UpdateAnimIK
// (BlueprintCallable, BlueprintEvent)

void UAB_Earwig_Augusta_C::UpdateAnimIK()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "UpdateAnimIK");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.UpdateCommon
// (BlueprintCallable, BlueprintEvent)

void UAB_Earwig_Augusta_C::UpdateCommon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "UpdateCommon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Earwig_Augusta.AB_Earwig_Augusta_C.UpdateIKTest
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UAB_Earwig_Augusta_C::UpdateIKTest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Earwig_Augusta_C", "UpdateIKTest");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
