#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Grub01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Maine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "PhysicsCore_structs.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass AB_Grub01.AB_Grub01_C
// 0x0550 (0x0A10 - 0x04C0)
class UAB_Grub01_C final : public UBurrowCharacterAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x04C8(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x04D0(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x04D8(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x04F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x0520(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x0548(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x0570(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x0598(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x05C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x05E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x0610(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x0638(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x0680(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x06A0(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x06E8(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x0708(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x0750(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x0770(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x07B8(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x07D8(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x0820(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0840(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x0888(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x08A8(0x00C8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0970(0x0048)()
	TMap<EPhysicalSurface, class UParticleSystem*> Surface_Impact_Map;                               // 0x09B8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void AnimNotify_Burrow();
	void AnimNotify_Unburrow();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Grub01_AnimGraphNode_TransitionResult_8E71986D4C2E90D20624538F8C54F424();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Grub01_AnimGraphNode_TransitionResult_E7894D21422A79FCF89039A5944145A4();
	void ExecuteUbergraph_AB_Grub01(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AB_Grub01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AB_Grub01_C")
	}
	static class UAB_Grub01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAB_Grub01_C>();
	}
};
DUMPER7_ASSERTS_UAB_Grub01_C;

SDK_NAMESPACE_END
