#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Hand_Scanner

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass AB_Hand_Scanner.AB_Hand_Scanner_C
// 0x0080 (0x0460 - 0x03E0)
class UAB_Hand_Scanner_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03E8(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03F0(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x03F8(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0418(0x0048)()

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_AB_Hand_Scanner(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AB_Hand_Scanner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AB_Hand_Scanner_C")
	}
	static class UAB_Hand_Scanner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAB_Hand_Scanner_C>();
	}
};
DUMPER7_ASSERTS_UAB_Hand_Scanner_C;

SDK_NAMESPACE_END
