#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Wasp01

#include "Basic.hpp"

#include "AB_Wasp01_classes.hpp"
#include "AB_Wasp01_parameters.hpp"


SDK_NAMESPACE_START

// Function AB_Wasp01.AB_Wasp01_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAB_Wasp01_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Wasp01_C", "AnimGraph");

	Params::AB_Wasp01_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AB_Wasp01.AB_Wasp01_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Wasp01_AnimGraphNode_TransitionResult_96F87A1F4CBDB58FF6751590384F51A1
// (BlueprintEvent)

void UAB_Wasp01_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Wasp01_AnimGraphNode_TransitionResult_96F87A1F4CBDB58FF6751590384F51A1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Wasp01_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Wasp01_AnimGraphNode_TransitionResult_96F87A1F4CBDB58FF6751590384F51A1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Wasp01.AB_Wasp01_C.ExecuteUbergraph_AB_Wasp01
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAB_Wasp01_C::ExecuteUbergraph_AB_Wasp01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Wasp01_C", "ExecuteUbergraph_AB_Wasp01");

	Params::AB_Wasp01_C_ExecuteUbergraph_AB_Wasp01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
