#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SpiderSaddle

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_SpiderSaddle.ABP_SpiderSaddle_C
// 0x01A0 (0x0580 - 0x03E0)
class UABP_SpiderSaddle_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03E8(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03F0(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x03F8(0x0020)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x0418(0x0158)(ContainsInstancedReference)
	class USkeletalMeshComponent*                 Mesh;                                              // 0x0570(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ABP_SpiderSaddle(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX_BlueprintUpdateAnimation);
	void BlueprintBeginPlay();
	void AnimGraph(struct FPoseLink* AnimGraph);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_SpiderSaddle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_SpiderSaddle_C")
	}
	static class UABP_SpiderSaddle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_SpiderSaddle_C>();
	}
};
DUMPER7_ASSERTS_UABP_SpiderSaddle_C;

SDK_NAMESPACE_END
