#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AntLeg_L_Front

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_AntLeg_L_Front.BP_AntLeg_L_Front_C.ExecuteUbergraph_BP_AntLeg_L_Front
// 0x0008 (0x0008 - 0x0000)
struct BP_AntLeg_L_Front_C_ExecuteUbergraph_BP_AntLeg_L_Front final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_AntLeg_L_Front_C_ExecuteUbergraph_BP_AntLeg_L_Front;

// Function BP_AntLeg_L_Front.BP_AntLeg_L_Front_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_AntLeg_L_Front_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_AntLeg_L_Front_C_ReceiveTick;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
