#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AntLeg_L_Front

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_InsectPart_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AntLeg_L_Front.BP_AntLeg_L_Front_C
// 0x0008 (0x0348 - 0x0340)
class ABP_AntLeg_L_Front_C final : public ABP_InsectPart_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_AntLeg_L_Front_C;                // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_AntLeg_L_Front(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AntLeg_L_Front_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AntLeg_L_Front_C")
	}
	static class ABP_AntLeg_L_Front_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AntLeg_L_Front_C>();
	}
};
DUMPER7_ASSERTS_ABP_AntLeg_L_Front_C;

SDK_NAMESPACE_END
