#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Backpack_Player_Male01

#include "Basic.hpp"

#include "BP_Backpack_Player_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Backpack_Player_Male01.BP_Backpack_Player_Male01_C
// 0x0000 (0x0448 - 0x0448)
class ABP_Backpack_Player_Male01_C final : public ABP_Backpack_Player_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Backpack_Player_Male01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Backpack_Player_Male01_C")
	}
	static class ABP_Backpack_Player_Male01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Backpack_Player_Male01_C>();
	}
};
DUMPER7_ASSERTS_ABP_Backpack_Player_Male01_C;

SDK_NAMESPACE_END
