#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Backpack_PostProcess

#include "Basic.hpp"

#include "BP_Backpack_PostProcess_classes.hpp"
#include "BP_Backpack_PostProcess_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Backpack_PostProcess.BP_Backpack_PostProcess_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UBP_Backpack_PostProcess_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Backpack_PostProcess_C", "AnimGraph");

	Params::BP_Backpack_PostProcess_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


SDK_NAMESPACE_END
