#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BlendTrigger_Hedge

#include "Basic.hpp"

#include "BP_BlendTrigger_Hedge_classes.hpp"
#include "BP_BlendTrigger_Hedge_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BlendTrigger_Hedge.BP_BlendTrigger_Hedge_C.ExecuteUbergraph_BP_BlendTrigger_Hedge
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BlendTrigger_Hedge_C::ExecuteUbergraph_BP_BlendTrigger_Hedge(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlendTrigger_Hedge_C", "ExecuteUbergraph_BP_BlendTrigger_Hedge");

	Params::BP_BlendTrigger_Hedge_C_ExecuteUbergraph_BP_BlendTrigger_Hedge Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BlendTrigger_Hedge.BP_BlendTrigger_Hedge_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BlendTrigger_Hedge_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlendTrigger_Hedge_C", "ReceiveTick");

	Params::BP_BlendTrigger_Hedge_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BlendTrigger_Hedge.BP_BlendTrigger_Hedge_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_BlendTrigger_Hedge_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BlendTrigger_Hedge_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
