#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cockroach_Queen_ORC

#include "Basic.hpp"

#include "BP_Cockroach_Queen_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Cockroach_Queen_ORC.BP_Cockroach_Queen_ORC_C
// 0x0000 (0x20D0 - 0x20D0)
class ABP_Cockroach_Queen_ORC_C : public ABP_Cockroach_Queen_C
{
public:
	class UChildActorComponent*                   ORC_Chip;                                          // 0x20C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Cockroach_Queen_ORC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Cockroach_Queen_ORC_C")
	}
	static class ABP_Cockroach_Queen_ORC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Cockroach_Queen_ORC_C>();
	}
};
DUMPER7_ASSERTS_ABP_Cockroach_Queen_ORC_C;

SDK_NAMESPACE_END
