#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FallbackEquippedItem

#include "Basic.hpp"

#include "BP_EquippedItem_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FallbackEquippedItem.BP_FallbackEquippedItem_C
// 0x0000 (0x06B8 - 0x06B8)
class ABP_FallbackEquippedItem_C final : public ABP_EquippedItem_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FallbackEquippedItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FallbackEquippedItem_C")
	}
	static class ABP_FallbackEquippedItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FallbackEquippedItem_C>();
	}
};
DUMPER7_ASSERTS_ABP_FallbackEquippedItem_C;

SDK_NAMESPACE_END
