#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GreenShieldBug_Augusta_ORC

#include "Basic.hpp"

#include "BP_GreenShieldBug_Augusta_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GreenShieldBug_Augusta_ORC.BP_GreenShieldBug_Augusta_ORC_C
// 0x0010 (0x2090 - 0x2080)
class ABP_GreenShieldBug_Augusta_ORC_C final : public ABP_GreenShieldBug_Augusta_C
{
public:
	class UChildActorComponent*                   ORC_Chip;                                          // 0x2080(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GreenShieldBug_Augusta_ORC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GreenShieldBug_Augusta_ORC_C")
	}
	static class ABP_GreenShieldBug_Augusta_ORC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GreenShieldBug_Augusta_ORC_C>();
	}
};
DUMPER7_ASSERTS_ABP_GreenShieldBug_Augusta_ORC_C;

SDK_NAMESPACE_END
