#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LDI_WaterSystem_PressureGauge

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OEIGlobalVariables_structs.hpp"
#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LDI_WaterSystem_PressureGauge.BP_LDI_WaterSystem_PressureGauge_C
// 0x0088 (0x0398 - 0x0310)
class ABP_LDI_WaterSystem_PressureGauge_C final : public ASwitch
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0310(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   SMT_PressureGauge_Glass;                           // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_PressureGauge_Dial;                             // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_PressureGauge;                                  // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_LeakRepair_DialProgress_860E1D914C51E92FC552B8814B3FCFF6; // 0x0340(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_LeakRepair__Direction_860E1D914C51E92FC552B8814B3FCFF6; // 0x0344(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_345[0x3];                                      // 0x0345(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_LeakRepair;                               // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_LeakActivation_DialProgress_7D671A444976B598613944B2A3C96995; // 0x0350(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_LeakActivation__Direction_7D671A444976B598613944B2A3C96995; // 0x0354(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_355[0x3];                                      // 0x0355(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_LeakActivation;                           // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_LDI_WaterSystem_Leak_C*>     WaterSystemLeaks;                                  // 0x0360(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	struct FGlobalVariableReference               ActivationGlobalVariable;                          // 0x0370(0x0010)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	double                                        AngleIncrementPerRepair;                           // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         DialRange;                                         // 0x0388(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumberOfLeaks;                                     // 0x038C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LeaksRepairedSoFar;                                // 0x0390(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ActivateLeaks(const struct FGuid& Guid, int32 GlobalValue);
	void ExecuteUbergraph_BP_LDI_WaterSystem_PressureGauge(int32 EntryPoint);
	void OnRepaired();
	void ReceiveBeginPlay();
	void SetDialPosition(double DialProgress, double AngleToCover);
	void SetInitialDialParentPosition(class USceneComponent* SceneComponent, int32 DialRange_0);
	void SetNumberOfLeaksAndAngle();
	void Timeline_LeakActivation__FinishedFunc();
	void Timeline_LeakActivation__UpdateFunc();
	void Timeline_LeakRepair__FinishedFunc();
	void Timeline_LeakRepair__UpdateFunc();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LDI_WaterSystem_PressureGauge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LDI_WaterSystem_PressureGauge_C")
	}
	static class ABP_LDI_WaterSystem_PressureGauge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LDI_WaterSystem_PressureGauge_C>();
	}
};
DUMPER7_ASSERTS_ABP_LDI_WaterSystem_PressureGauge_C;

SDK_NAMESPACE_END
