#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LDI_Water_Intake_LizardArena

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_LDI_Water_Intake_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LDI_Water_Intake_LizardArena.BP_LDI_Water_Intake_LizardArena_C
// 0x0008 (0x0958 - 0x0950)
class ABP_LDI_Water_Intake_LizardArena_C final : public ABP_LDI_Water_Intake_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_LDI_Water_Intake_LizardArena_C;  // 0x0950(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_LDI_Water_Intake_LizardArena(int32 EntryPoint);
	void OnBuildingRepaired(class AActor* InstigatedBy);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LDI_Water_Intake_LizardArena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LDI_Water_Intake_LizardArena_C")
	}
	static class ABP_LDI_Water_Intake_LizardArena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LDI_Water_Intake_LizardArena_C>();
	}
};
DUMPER7_ASSERTS_ABP_LDI_Water_Intake_LizardArena_C;

SDK_NAMESPACE_END
