#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lab_Door_A_Simple

#include "Basic.hpp"

#include "BP_Lab_Door_A_Simple_classes.hpp"
#include "BP_Lab_Door_A_Simple_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Lab_Door_A_Simple.BP_Lab_Door_A_Simple_C.ExecuteUbergraph_BP_Lab_Door_A_Simple
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lab_Door_A_Simple_C::ExecuteUbergraph_BP_Lab_Door_A_Simple(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lab_Door_A_Simple_C", "ExecuteUbergraph_BP_Lab_Door_A_Simple");

	Params::BP_Lab_Door_A_Simple_C_ExecuteUbergraph_BP_Lab_Door_A_Simple Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Lab_Door_A_Simple.BP_Lab_Door_A_Simple_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Lab_Door_A_Simple_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lab_Door_A_Simple_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lab_Door_A_Simple.BP_Lab_Door_A_Simple_C.SetVisual
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Lab_Door_A_Simple_C::SetVisual()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lab_Door_A_Simple_C", "SetVisual");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lab_Door_A_Simple.BP_Lab_Door_A_Simple_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Lab_Door_A_Simple_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lab_Door_A_Simple_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lab_Door_A_Simple.BP_Lab_Door_A_Simple_C.ShouldSave
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Lab_Door_A_Simple_C::ShouldSave() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lab_Door_A_Simple_C", "ShouldSave");

	Params::BP_Lab_Door_A_Simple_C_ShouldSave Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
