#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lab_Control_Panel_Standing_Light_StripDouble

#include "Basic.hpp"

#include "BP_LightFixture_Flicker_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Lab_Control_Panel_Standing_Light_StripDouble.BP_Lab_Control_Panel_Standing_Light_StripDouble_C
// 0x0018 (0x0418 - 0x0400)
class ABP_Lab_Control_Panel_Standing_Light_StripDouble_C final : public ABP_LightFixture_Flicker_C
{
public:
	class UStaticMeshComponent*                   SM_Lab_Control_Panel_Standing_Light_Strip1;        // 0x0400(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight;                                         // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Lab_Control_Panel_Standing_Light_Strip;         // 0x0410(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Lab_Control_Panel_Standing_Light_StripDouble_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Lab_Control_Panel_Standing_Light_StripDouble_C")
	}
	static class ABP_Lab_Control_Panel_Standing_Light_StripDouble_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lab_Control_Panel_Standing_Light_StripDouble_C>();
	}
};
DUMPER7_ASSERTS_ABP_Lab_Control_Panel_Standing_Light_StripDouble_C;

SDK_NAMESPACE_END
