#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LDI_BlackWire_Power_Leak

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_LDI_BlackWire_Power_Leak.BP_LDI_BlackWire_Power_Leak_C.ExecuteUbergraph_BP_LDI_BlackWire_Power_Leak
// 0x0008 (0x0008 - 0x0000)
struct BP_LDI_BlackWire_Power_Leak_C_ExecuteUbergraph_BP_LDI_BlackWire_Power_Leak final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocked_ReturnValue;                     // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_LDI_BlackWire_Power_Leak_C_ExecuteUbergraph_BP_LDI_BlackWire_Power_Leak;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
