#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LDI_Greenhouse_GrowNeon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OEIGlobalVariables_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LDI_Greenhouse_GrowNeon.BP_LDI_Greenhouse_GrowNeon_C
// 0x0098 (0x03A8 - 0x0310)
class ABP_LDI_Greenhouse_GrowNeon_C final : public ASwitch
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0310(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDecalComponent*                        Decal;                                             // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_LDI_Greenhouse_GrowNeon_ChainEnd_02;            // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_LDI_Greenhouse_GrowNeon_ChainEnd_01;            // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_LDI_Greenhouse_GrowNeon_Neon;                   // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_LDI_Greenhouse_GrowNeon_Housing;                // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Timeline_LightIntensity_GlowColor01_596D1A9D408F6D652AC0E2B50BA0578B; // 0x0348(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_LightIntensity_Progress_596D1A9D408F6D652AC0E2B50BA0578B; // 0x0360(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_LightIntensity__Direction_596D1A9D408F6D652AC0E2B50BA0578B; // 0x0364(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_365[0x3];                                      // 0x0365(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_LightIntensity;                           // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsActivated;                                      // 0x0370(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_371[0x3];                                      // 0x0371(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGlobalVariableReference               ActivationGlobalVariable;                          // 0x0374(0x0010)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_384[0x4];                                      // 0x0384(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               Mid;                                               // 0x0388(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        LightIntensityMultiplier;                          // 0x0390(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnActivated;                                       // 0x0398(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Activate(const struct FGuid& Guid, int32 GlobalValue);
	void BndEvt__BP_GrowLamp_01_OCLComponent_K2Node_ComponentBoundEvent_0_OpenStateChangedDelegate__DelegateSignature(bool IsOpen, class AActor* Instigator_0);
	void ExecuteUbergraph_BP_LDI_Greenhouse_GrowNeon(int32 EntryPoint);
	void OnRep_bIsActivated();
	void ReceiveBeginPlay();
	void SetLightIntensity(double Intensity_0_1, const struct FVector& GlowColor01);
	void Timeline_LightIntensity__FinishedFunc();
	void Timeline_LightIntensity__UpdateFunc();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LDI_Greenhouse_GrowNeon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LDI_Greenhouse_GrowNeon_C")
	}
	static class ABP_LDI_Greenhouse_GrowNeon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LDI_Greenhouse_GrowNeon_C>();
	}
};
DUMPER7_ASSERTS_ABP_LDI_Greenhouse_GrowNeon_C;

SDK_NAMESPACE_END
