#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LDI_WaterSystem_BallValve_Watercooling_Puzzle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OEIGlobalVariables_structs.hpp"
#include "OEIFlowCharts_structs.hpp"
#include "Maine_structs.hpp"
#include "Maine_classes.hpp"
#include "OEIText_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LDI_WaterSystem_BallValve_Watercooling_Puzzle.BP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_C
// 0x00F0 (0x0400 - 0x0310)
class ABP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_C final : public ASwitch
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0310(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        PushDirection;                                     // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UConditionalToggleComponent*            ConditionalToggle_ActivateInteraction;             // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Audio_Activation;                                  // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_LDI_WaterSystem_BallValve;                      // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_Progression_56923DD44524EB6B802E28A50EDFE100; // 0x0350(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_56923DD44524EB6B802E28A50EDFE100; // 0x0354(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_355[0x3];                                      // 0x0355(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          IsActivated;                                       // 0x0360(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361[0x3];                                      // 0x0361(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLocString                             InteractionText_Activate;                          // 0x0364(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_374[0x4];                                      // 0x0374(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 ActorInstigator;                                   // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnActivated;                                       // 0x0380(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          InteractionIsEnabled;                              // 0x0390(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_391[0x3];                                      // 0x0391(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGlobalVariableReference               Global_Variable_To_Set;                            // 0x0394(0x0010)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	int32                                         Value;                                             // 0x03A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ANiagaraActor*>                  AdditionnalVFX;                                    // 0x03A8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	bool                                          RequestAutoSaveOnComplete;                         // 0x03B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B9[0x3];                                      // 0x03B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLocString                             InteractionText_Locked;                            // 0x03BC(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3CC[0x4];                                      // 0x03CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_SurvivalPlayerCharacter_C*          PotentiallyCrushedActor;                           // 0x03D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        PushForce;                                         // 0x03D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FConversationReference                 Conversation;                                      // 0x03E0(0x0018)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	int32                                         NodeId;                                            // 0x03F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EConversationPlayPriority                     Priority;                                          // 0x03FC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_LDI_WaterSystem_BallValve_ConditionalToggle_K2Node_ComponentBoundEvent_0_OnConditionalStateChanged__DelegateSignature(bool bIsActive);
	void BndEvt__BP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__BP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_Box_K2Node_ComponentBoundEvent_2_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void ExecuteUbergraph_BP_LDI_WaterSystem_BallValve_Watercooling_Puzzle(int32 EntryPoint);
	void OnOpenStateChanged(bool IsOpen, class AActor* ActorInstigator_0);
	void OnRep_InteractionIsEnabled();
	void OnRep_IsActivated();
	void PushPlayerOutOfTheWay();
	void ReceiveBeginPlay();
	void SetValveRotation(double Progression);
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();

	void GetInteractionText(EInteractionChannel Channel, const class AActor* InstigatedBy, class FString* OutText) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_C")
	}
	static class ABP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_C>();
	}
};
DUMPER7_ASSERTS_ABP_LDI_WaterSystem_BallValve_Watercooling_Puzzle_C;

SDK_NAMESPACE_END
