#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Milkweed_Pod_01_Fallen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_StaticHarvestNode_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Milkweed_Pod_01_Fallen.BP_Milkweed_Pod_01_Fallen_C
// 0x0008 (0x04B8 - 0x04B0)
class ABP_Milkweed_Pod_01_Fallen_C final : public ABP_StaticHarvestNode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Milkweed_Pod_01_Fallen_C;        // 0x04B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Milkweed_Pod_01_Fallen(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Milkweed_Pod_01_Fallen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Milkweed_Pod_01_Fallen_C")
	}
	static class ABP_Milkweed_Pod_01_Fallen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Milkweed_Pod_01_Fallen_C>();
	}
};
DUMPER7_ASSERTS_ABP_Milkweed_Pod_01_Fallen_C;

SDK_NAMESPACE_END
