#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Milkweed_Pod_01_Physics

#include "Basic.hpp"

#include "BP_PhysicsHarvestNode_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Milkweed_Pod_01_Physics.BP_Milkweed_Pod_01_Physics_C
// 0x0000 (0x0470 - 0x0470)
class ABP_Milkweed_Pod_01_Physics_C final : public ABP_PhysicsHarvestNode_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Milkweed_Pod_01_Physics_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Milkweed_Pod_01_Physics_C")
	}
	static class ABP_Milkweed_Pod_01_Physics_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Milkweed_Pod_01_Physics_C>();
	}
};
DUMPER7_ASSERTS_ABP_Milkweed_Pod_01_Physics_C;

SDK_NAMESPACE_END
