#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RawScienceUI

#include "Basic.hpp"

#include "BP_RawScienceUI_classes.hpp"
#include "BP_RawScienceUI_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_RawScienceUI.BP_RawScienceUI_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_RawScienceUI_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RawScienceUI_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RawScienceUI.BP_RawScienceUI_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_RawScienceUI_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RawScienceUI_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RawScienceUI.BP_RawScienceUI_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_RawScienceUI_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RawScienceUI_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RawScienceUI.BP_RawScienceUI_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds_ReceiveTick                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RawScienceUI_C::ReceiveTick(float DeltaSeconds_ReceiveTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RawScienceUI_C", "ReceiveTick");

	Params::BP_RawScienceUI_C_ReceiveTick Parms{};

	Parms.DeltaSeconds_ReceiveTick = DeltaSeconds_ReceiveTick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RawScienceUI.BP_RawScienceUI_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_RawScienceUI_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RawScienceUI_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RawScienceUI.BP_RawScienceUI_C.ExecuteUbergraph_BP_RawScienceUI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RawScienceUI_C::ExecuteUbergraph_BP_RawScienceUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RawScienceUI_C", "ExecuteUbergraph_BP_RawScienceUI");

	Params::BP_RawScienceUI_C_ExecuteUbergraph_BP_RawScienceUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
