#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SmallPlantB_Dry

#include "Basic.hpp"

#include "BP_SmallPlantA_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SmallPlantB_Dry.BP_SmallPlantB_Dry_C
// 0x0000 (0x06A8 - 0x06A8)
class ABP_SmallPlantB_Dry_C final : public ABP_SmallPlantA_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SmallPlantB_Dry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SmallPlantB_Dry_C")
	}
	static class ABP_SmallPlantB_Dry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SmallPlantB_Dry_C>();
	}
};
DUMPER7_ASSERTS_ABP_SmallPlantB_Dry_C;

SDK_NAMESPACE_END
