#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SurvivalPlayerState_Augusta

#include "Basic.hpp"

#include "BP_SurvivalPlayerState_Augusta_classes.hpp"
#include "BP_SurvivalPlayerState_Augusta_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_SurvivalPlayerState_Augusta.BP_SurvivalPlayerState_Augusta_C.CreateHotPouchSlots
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SurvivalPlayerState_Augusta_C::CreateHotPouchSlots()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SurvivalPlayerState_Augusta_C", "CreateHotPouchSlots");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SurvivalPlayerState_Augusta.BP_SurvivalPlayerState_Augusta_C.CreateMountSlots
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SurvivalPlayerState_Augusta_C::CreateMountSlots()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SurvivalPlayerState_Augusta_C", "CreateMountSlots");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SurvivalPlayerState_Augusta.BP_SurvivalPlayerState_Augusta_C.ExecuteUbergraph_BP_SurvivalPlayerState_Augusta
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SurvivalPlayerState_Augusta_C::ExecuteUbergraph_BP_SurvivalPlayerState_Augusta(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SurvivalPlayerState_Augusta_C", "ExecuteUbergraph_BP_SurvivalPlayerState_Augusta");

	Params::BP_SurvivalPlayerState_Augusta_C_ExecuteUbergraph_BP_SurvivalPlayerState_Augusta Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SurvivalPlayerState_Augusta.BP_SurvivalPlayerState_Augusta_C.PlayStartupTutorials
// (BlueprintCallable, BlueprintEvent)

void ABP_SurvivalPlayerState_Augusta_C::PlayStartupTutorials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SurvivalPlayerState_Augusta_C", "PlayStartupTutorials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SurvivalPlayerState_Augusta.BP_SurvivalPlayerState_Augusta_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_SurvivalPlayerState_Augusta_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SurvivalPlayerState_Augusta_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SurvivalPlayerState_Augusta.BP_SurvivalPlayerState_Augusta_C.StartMilkMolarTutorialCooldown
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECollectibleType                        EMolarType_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SurvivalPlayerState_Augusta_C::StartMilkMolarTutorialCooldown(ECollectibleType EMolarType_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SurvivalPlayerState_Augusta_C", "StartMilkMolarTutorialCooldown");

	Params::BP_SurvivalPlayerState_Augusta_C_StartMilkMolarTutorialCooldown Parms{};

	Parms.EMolarType_0 = EMolarType_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SurvivalPlayerState_Augusta.BP_SurvivalPlayerState_Augusta_C.StartRootLDITutorialCooldown
// (BlueprintCallable, BlueprintEvent)

void ABP_SurvivalPlayerState_Augusta_C::StartRootLDITutorialCooldown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SurvivalPlayerState_Augusta_C", "StartRootLDITutorialCooldown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SurvivalPlayerState_Augusta.BP_SurvivalPlayerState_Augusta_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_SurvivalPlayerState_Augusta_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SurvivalPlayerState_Augusta_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
