#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Spider_Web_Augusta_Buggy

#include "Basic.hpp"

#include "BP_Spider_Web_Augusta_Buggy_classes.hpp"
#include "BP_Spider_Web_Augusta_Buggy_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Spider_Web_Augusta_Buggy.BP_Spider_Web_Augusta_Buggy_C.BndEvt__BP_SurvivalPlayerCharacter_CharMovementComponent_K2Node_ComponentBoundEvent_4_OnGliderMovementModeChangedDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsGliding                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Spider_Web_Augusta_Buggy_C::BndEvt__BP_SurvivalPlayerCharacter_CharMovementComponent_K2Node_ComponentBoundEvent_4_OnGliderMovementModeChangedDelegate__DelegateSignature(bool bIsGliding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spider_Web_Augusta_Buggy_C", "BndEvt__BP_SurvivalPlayerCharacter_CharMovementComponent_K2Node_ComponentBoundEvent_4_OnGliderMovementModeChangedDelegate__DelegateSignature");

	Params::BP_Spider_Web_Augusta_Buggy_C_BndEvt__BP_SurvivalPlayerCharacter_CharMovementComponent_K2Node_ComponentBoundEvent_4_OnGliderMovementModeChangedDelegate__DelegateSignature Parms{};

	Parms.bIsGliding = bIsGliding;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spider_Web_Augusta_Buggy.BP_Spider_Web_Augusta_Buggy_C.ExecuteUbergraph_BP_Spider_Web_Augusta_Buggy
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Spider_Web_Augusta_Buggy_C::ExecuteUbergraph_BP_Spider_Web_Augusta_Buggy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spider_Web_Augusta_Buggy_C", "ExecuteUbergraph_BP_Spider_Web_Augusta_Buggy");

	Params::BP_Spider_Web_Augusta_Buggy_C_ExecuteUbergraph_BP_Spider_Web_Augusta_Buggy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spider_Web_Augusta_Buggy.BP_Spider_Web_Augusta_Buggy_C.OnAttackLaunched
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAttack*                          Attack                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Spider_Web_Augusta_Buggy_C::OnAttackLaunched(class UAttack* Attack)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spider_Web_Augusta_Buggy_C", "OnAttackLaunched");

	Params::BP_Spider_Web_Augusta_Buggy_C_OnAttackLaunched Parms{};

	Parms.Attack = Attack;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spider_Web_Augusta_Buggy.BP_Spider_Web_Augusta_Buggy_C.OnCharacterWebbed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASurvivalCharacter*               WebbedCharacter                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Spider_Web_Augusta_Buggy_C::OnCharacterWebbed(class ASurvivalCharacter* WebbedCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spider_Web_Augusta_Buggy_C", "OnCharacterWebbed");

	Params::BP_Spider_Web_Augusta_Buggy_C_OnCharacterWebbed Parms{};

	Parms.WebbedCharacter = WebbedCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spider_Web_Augusta_Buggy.BP_Spider_Web_Augusta_Buggy_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Spider_Web_Augusta_Buggy_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spider_Web_Augusta_Buggy_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Spider_Web_Augusta_Buggy.BP_Spider_Web_Augusta_Buggy_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Spider_Web_Augusta_Buggy_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spider_Web_Augusta_Buggy_C", "ReceiveEndPlay");

	Params::BP_Spider_Web_Augusta_Buggy_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spider_Web_Augusta_Buggy.BP_Spider_Web_Augusta_Buggy_C.UpdateGliderVisibility
// (BlueprintCallable, BlueprintEvent)

void ABP_Spider_Web_Augusta_Buggy_C::UpdateGliderVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spider_Web_Augusta_Buggy_C", "UpdateGliderVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
