#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SwimmingSurvivalCreature_Base

#include "Basic.hpp"

#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SwimmingSurvivalCreature_Base.BP_SwimmingSurvivalCreature_Base_C
// 0x0000 (0x3410 - 0x3410)
class ABP_SwimmingSurvivalCreature_Base_C : public ASwimmingSurvivalCharacter
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SwimmingSurvivalCreature_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SwimmingSurvivalCreature_Base_C")
	}
	static class ABP_SwimmingSurvivalCreature_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SwimmingSurvivalCreature_Base_C>();
	}
};
DUMPER7_ASSERTS_ABP_SwimmingSurvivalCreature_Base_C;

SDK_NAMESPACE_END
