#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SweetPotato_Rotten_A

#include "Basic.hpp"

#include "BP_StaticHarvestNode_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SweetPotato_Rotten_A.BP_SweetPotato_Rotten_A_C
// 0x0000 (0x04B0 - 0x04B0)
class ABP_SweetPotato_Rotten_A_C final : public ABP_StaticHarvestNode_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SweetPotato_Rotten_A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SweetPotato_Rotten_A_C")
	}
	static class ABP_SweetPotato_Rotten_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SweetPotato_Rotten_A_C>();
	}
};
DUMPER7_ASSERTS_ABP_SweetPotato_Rotten_A_C;

SDK_NAMESPACE_END
