#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Switch_CableRepair_MQ02

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OEICommon_structs.hpp"
#include "Maine_structs.hpp"
#include "Maine_classes.hpp"
#include "OEIText_structs.hpp"
#include "OEIGlobalVariables_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Switch_CableRepair_MQ02.BP_Switch_CableRepair_MQ02_C
// 0x0060 (0x0370 - 0x0310)
class ABP_Switch_CableRepair_MQ02_C final : public ASwitch
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0310(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UChildActorComponent*                   VFX_Spark_01;                                      // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CableMID;                                          // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FLocString                             InteractionText_Repair;                            // 0x0330(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxRepair;                                         // 0x0340(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLocString                             NewVar;                                            // 0x0344(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRepaired;                                        // 0x0354(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_355[0x3];                                      // 0x0355(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 Actor_Instigator;                                  // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGlobalVariableReference               GlobalVar_RelayCableRepair;                        // 0x0360(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Switch_CableRepair_MQ02(int32 EntryPoint);
	void OnOpenStateChanged(bool IsOpen, class AActor* ActorInstigator);
	void OnRep_IsRepaired();
	void PlayVO();
	void ReceiveBeginPlay();

	void GetInteractionText(EInteractionChannel Channel, const class AActor* InstigatedBy, class FString* OutText) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Switch_CableRepair_MQ02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Switch_CableRepair_MQ02_C")
	}
	static class ABP_Switch_CableRepair_MQ02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Switch_CableRepair_MQ02_C>();
	}
};
DUMPER7_ASSERTS_ABP_Switch_CableRepair_MQ02_C;

SDK_NAMESPACE_END
