#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Siren_Light_GrowingPod

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Siren_Light_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Siren_Light_GrowingPod.BP_Siren_Light_GrowingPod_C
// 0x0020 (0x0420 - 0x0400)
class ABP_Siren_Light_GrowingPod_C final : public ABP_Siren_Light_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Siren_Light_GrowingPod_C;        // 0x0400(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Timeline_Alpha_2E78EDC7497CA9A3F1782299640511DB;   // 0x0408(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_2E78EDC7497CA9A3F1782299640511DB; // 0x040C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40D[0x3];                                      // 0x040D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x0410(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bStartActive;                                      // 0x0418(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ActivateSiren();
	void DeactivateSiren();
	void ExecuteUbergraph_BP_Siren_Light_GrowingPod(int32 EntryPoint);
	void ReceiveBeginPlay();
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Siren_Light_GrowingPod_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Siren_Light_GrowingPod_C")
	}
	static class ABP_Siren_Light_GrowingPod_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Siren_Light_GrowingPod_C>();
	}
};
DUMPER7_ASSERTS_ABP_Siren_Light_GrowingPod_C;

SDK_NAMESPACE_END
