#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trap_Cactus_A

#include "Basic.hpp"

#include "BP_Trap_Cactus_A_classes.hpp"
#include "BP_Trap_Cactus_A_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Trap_Cactus_A.BP_Trap_Cactus_A_C.IsInteractionEnabled
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// EInteractionChannel                     Channel                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class AActor*                     InstigatedBy                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EInteractionState                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EInteractionState ABP_Trap_Cactus_A_C::IsInteractionEnabled(EInteractionChannel Channel, const class AActor* InstigatedBy) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Trap_Cactus_A_C", "IsInteractionEnabled");

	Params::BP_Trap_Cactus_A_C_IsInteractionEnabled Parms{};

	Parms.Channel = Channel;
	Parms.InstigatedBy = InstigatedBy;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
