#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VFX_Bombardier_Loot

#include "Basic.hpp"

#include "BP_VFX_Bombardier_Loot_classes.hpp"
#include "BP_VFX_Bombardier_Loot_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_VFX_Bombardier_Loot.BP_VFX_Bombardier_Loot_C.ExecuteUbergraph_BP_VFX_Bombardier_Loot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_VFX_Bombardier_Loot_C::ExecuteUbergraph_BP_VFX_Bombardier_Loot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VFX_Bombardier_Loot_C", "ExecuteUbergraph_BP_VFX_Bombardier_Loot");

	Params::BP_VFX_Bombardier_Loot_C_ExecuteUbergraph_BP_VFX_Bombardier_Loot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VFX_Bombardier_Loot.BP_VFX_Bombardier_Loot_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_VFX_Bombardier_Loot_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VFX_Bombardier_Loot_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
