#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_World_Pollen

#include "Basic.hpp"

#include "BP_WorldItem_classes.hpp"
#include "Maine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_World_Pollen.BP_World_Pollen_C
// 0x0000 (0x06A8 - 0x06A8)
class ABP_World_Pollen_C final : public ABP_WorldItem_C
{
public:
	EInteractionState IsInteractionEnabled(EInteractionChannel Channel, const class AActor* InstigatedBy) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_World_Pollen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_World_Pollen_C")
	}
	static class ABP_World_Pollen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_World_Pollen_C>();
	}
};
DUMPER7_ASSERTS_ABP_World_Pollen_C;

SDK_NAMESPACE_END
