#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Weevil

#include "Basic.hpp"

#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Weevil.BP_Weevil_C
// 0x0040 (0x2060 - 0x2020)
class ABP_Weevil_C final : public ASurvivalCreature
{
public:
	class UWidgetInteractComponent*               WidgetInteract;                                    // 0x2020(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInventoryComponent*                    Inventory;                                         // 0x2028(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UEquipmentComponent*                    Equipment;                                         // 0x2030(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 HeadArmorMeshComponent;                            // 0x2038(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPlayerLookTriggerComponent*            LookTrigger;                                       // 0x2040(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBanterStarterComponent*                BanterStarter;                                     // 0x2048(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ULootComponent*                         Loot;                                              // 0x2050(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Weevil_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Weevil_C")
	}
	static class ABP_Weevil_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Weevil_C>();
	}
};
DUMPER7_ASSERTS_ABP_Weevil_C;

SDK_NAMESPACE_END
