#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_World_Slimemold_Stalk_B

#include "Basic.hpp"

#include "BP_WorldItem_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_World_Slimemold_Stalk_B.BP_World_Slimemold_Stalk_B_C
// 0x0008 (0x06B0 - 0x06A8)
class ABP_World_Slimemold_Stalk_B_C final : public ABP_WorldItem_C
{
public:
	class UPointLightComponent*                   PointLight;                                        // 0x06A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_World_Slimemold_Stalk_B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_World_Slimemold_Stalk_B_C")
	}
	static class ABP_World_Slimemold_Stalk_B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_World_Slimemold_Stalk_B_C>();
	}
};
DUMPER7_ASSERTS_ABP_World_Slimemold_Stalk_B_C;

SDK_NAMESPACE_END
