#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_VisualCustomization

#include "Basic.hpp"

#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPC_VisualCustomization.BPC_VisualCustomization_C
// 0x0000 (0x0158 - 0x0158)
class UBPC_VisualCustomization_C final : public UVisualCustomizationComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_VisualCustomization_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_VisualCustomization_C")
	}
	static class UBPC_VisualCustomization_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_VisualCustomization_C>();
	}
};
DUMPER7_ASSERTS_UBPC_VisualCustomization_C;

SDK_NAMESPACE_END
