#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPF_VFX_Utilities

#include "Basic.hpp"

#include "BPF_VFX_Utilities_classes.hpp"
#include "BPF_VFX_Utilities_parameters.hpp"


SDK_NAMESPACE_START

// Function BPF_VFX_Utilities.BPF_VFX_Utilities_C.ApplyGenericParameters
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UNiagaraComponent*                Niagara_System                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UBPA_NiagaraUserParameters_C*     Config                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPF_VFX_Utilities_C::ApplyGenericParameters(class UNiagaraComponent* Niagara_System, class UBPA_NiagaraUserParameters_C* Config, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPF_VFX_Utilities_C", "ApplyGenericParameters");

	Params::BPF_VFX_Utilities_C_ApplyGenericParameters Parms{};

	Parms.Niagara_System = Niagara_System;
	Parms.Config = Config;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPF_VFX_Utilities.BPF_VFX_Utilities_C.AssignSkeletalMesh
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UNiagaraComponent*                NiagaraSystem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FString&                    UserParameterName                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class USkeletalMeshComponent*           SkeletalMesh                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPF_VFX_Utilities_C::AssignSkeletalMesh(class UNiagaraComponent* NiagaraSystem, const class FString& UserParameterName, class USkeletalMeshComponent* SkeletalMesh, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPF_VFX_Utilities_C", "AssignSkeletalMesh");

	Params::BPF_VFX_Utilities_C_AssignSkeletalMesh Parms{};

	Parms.NiagaraSystem = NiagaraSystem;
	Parms.UserParameterName = std::move(UserParameterName);
	Parms.SkeletalMesh = SkeletalMesh;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPF_VFX_Utilities.BPF_VFX_Utilities_C.GetApproximateSplineBounds
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USplineComponent*                 Spline                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Samples                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         MinBounds                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         MaxBounds                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPF_VFX_Utilities_C::GetApproximateSplineBounds(class USplineComponent* Spline, int32 Samples, class UObject* __WorldContext, struct FVector* MinBounds, struct FVector* MaxBounds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPF_VFX_Utilities_C", "GetApproximateSplineBounds");

	Params::BPF_VFX_Utilities_C_GetApproximateSplineBounds Parms{};

	Parms.Spline = Spline;
	Parms.Samples = Samples;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (MinBounds != nullptr)
		*MinBounds = std::move(Parms.MinBounds);

	if (MaxBounds != nullptr)
		*MaxBounds = std::move(Parms.MaxBounds);
}


SDK_NAMESPACE_END
