#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BQ_Craft5StickySmoothies

#include "Basic.hpp"

#include "BQT_CraftQuestBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BQ_Craft5StickySmoothies.BQ_Craft5StickySmoothies_C
// 0x0000 (0x00D0 - 0x00D0)
class UBQ_Craft5StickySmoothies_C final : public UBQT_CraftQuestBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BQ_Craft5StickySmoothies_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BQ_Craft5StickySmoothies_C")
	}
	static class UBQ_Craft5StickySmoothies_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBQ_Craft5StickySmoothies_C>();
	}
};
DUMPER7_ASSERTS_UBQ_Craft5StickySmoothies_C;

SDK_NAMESPACE_END
