#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BQT_StatQuestBase

#include "Basic.hpp"

#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BQT_StatQuestBase.BQT_StatQuestBase_C
// 0x0000 (0x00D0 - 0x00D0)
class UBQT_StatQuestBase_C : public UBurgleQuest2Stat
{
public:
	class FString GetObjectiveText(int32 ObjectiveIndex) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BQT_StatQuestBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BQT_StatQuestBase_C")
	}
	static class UBQT_StatQuestBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBQT_StatQuestBase_C>();
	}
};
DUMPER7_ASSERTS_UBQT_StatQuestBase_C;

SDK_NAMESPACE_END
