#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CR_SpiderWebShield

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ControlRig_structs.hpp"
#include "ControlRig_classes.hpp"
#include "RigVM_structs.hpp"
#include "RigVM_classes.hpp"


SDK_NAMESPACE_START

// RigVMMemoryStorageGeneratorClass CR_SpiderWebShield.RigVMMemory_Work
// 0x03D8 (0x0400 - 0x0028)
class CR_SpiderWebShield::URigVMMemory_Work final : public URigVMMemoryStorage
{
public:
	struct FVector                                RigVMModel___VerletIntegrateVector_Position;       // 0x0028(0x0018)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FVector                                RigVMModel___Interpolate_Result;                   // 0x0040(0x0018)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58[0x8];                                       // 0x0058(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             RigVMModel___RigUnit_GetTransform_Transform;       // 0x0060(0x0060)(Edit, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___RigUnit_GetTransform_CachedIndex;     // 0x00C0(0x0010)(Edit, EditConst, NonTransactional)
	struct FVector                                RigVMModel___Interpolate_A;                        // 0x00D0(0x0018)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E8[0x8];                                       // 0x00E8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             RigVMModel___RigUnit_GetTransform_1_Transform;     // 0x00F0(0x0060)(Edit, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___RigUnit_GetTransform_1_CachedIndex;   // 0x0150(0x0010)(Edit, EditConst, NonTransactional)
	struct FVector                                RigVMModel___Interpolate_B;                        // 0x0160(0x0018)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FVector                                RigVMModel___VerletIntegrateVector_Velocity;       // 0x0178(0x0018)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FVector                                RigVMModel___VerletIntegrateVector_Acceleration;   // 0x0190(0x0018)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FRigVMSimPoint>                 RigVMModel___VerletIntegrateVector_Point;          // 0x01A8(0x0010)(Edit, EditConst, NonTransactional)
	TArray<bool>                                  RigVMModel___VerletIntegrateVector_bInitialized;   // 0x01B8(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___RigUnit_SetTranslation_CachedIndex;   // 0x01C8(0x0010)(Edit, EditConst, NonTransactional)
	struct FRigUnit_AimItem_Target                RigVMModel___AimItem_Primary__IO;                  // 0x01D8(0x0048)(Edit, EditConst, NonTransactional, NoDestructor)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_CachedItem;                   // 0x0220(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_PrimaryCachedSpace;           // 0x0230(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_SecondaryCachedSpace;         // 0x0240(0x0010)(Edit, EditConst, NonTransactional)
	TArray<bool>                                  RigVMModel___AimItem_bIsInitialized;               // 0x0250(0x0010)(Edit, EditConst, NonTransactional)
	struct FRigUnit_AimItem_Target                RigVMModel___AimItem_1_Primary__IO;                // 0x0260(0x0048)(Edit, EditConst, NonTransactional, NoDestructor)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_CachedItem;                 // 0x02A8(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_PrimaryCachedSpace;         // 0x02B8(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_SecondaryCachedSpace;       // 0x02C8(0x0010)(Edit, EditConst, NonTransactional)
	TArray<bool>                                  RigVMModel___AimItem_1_bIsInitialized;             // 0x02D8(0x0010)(Edit, EditConst, NonTransactional)
	struct FRigUnit_AimItem_Target                RigVMModel___AimItem_1_1_Primary__IO;              // 0x02E8(0x0048)(Edit, EditConst, NonTransactional, NoDestructor)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_1_CachedItem;               // 0x0330(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_1_PrimaryCachedSpace;       // 0x0340(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_1_SecondaryCachedSpace;     // 0x0350(0x0010)(Edit, EditConst, NonTransactional)
	TArray<bool>                                  RigVMModel___AimItem_1_1_bIsInitialized;           // 0x0360(0x0010)(Edit, EditConst, NonTransactional)
	struct FRigUnit_AimItem_Target                RigVMModel___AimItem_1_2_Primary__IO;              // 0x0370(0x0048)(Edit, EditConst, NonTransactional, NoDestructor)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_2_CachedItem;               // 0x03B8(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_2_PrimaryCachedSpace;       // 0x03C8(0x0010)(Edit, EditConst, NonTransactional)
	TArray<struct FCachedRigElement>              RigVMModel___AimItem_1_2_SecondaryCachedSpace;     // 0x03D8(0x0010)(Edit, EditConst, NonTransactional)
	TArray<bool>                                  RigVMModel___AimItem_1_2_bIsInitialized;           // 0x03E8(0x0010)(Edit, EditConst, NonTransactional)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL_FULLNAME("RigVMMemoryStorageGeneratorClass CR_SpiderWebShield.RigVMMemory_Work")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RigVMMemory_Work")
	}
	static class CR_SpiderWebShield::URigVMMemory_Work* GetDefaultObj()
	{
		return GetDefaultObjImpl<CR_SpiderWebShield::URigVMMemory_Work>();
	}
};
DUMPER7_ASSERTS_CR_SpiderWebShield__URigVMMemory_Work;

// ControlRigBlueprintGeneratedClass CR_SpiderWebShield.CR_SpiderWebShield_C
// 0x0000 (0x0B70 - 0x0B70)
class UCR_SpiderWebShield_C final : public UControlRig
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CR_SpiderWebShield_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CR_SpiderWebShield_C")
	}
	static class UCR_SpiderWebShield_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCR_SpiderWebShield_C>();
	}
};
DUMPER7_ASSERTS_UCR_SpiderWebShield_C;

// RigVMMemoryStorageGeneratorClass CR_SpiderWebShield.RigVMMemory_Literal
// 0x01C8 (0x01F0 - 0x0028)
class CR_SpiderWebShield::URigVMMemory_Literal final : public URigVMMemoryStorage
{
public:
	struct FRigElementKey                         RigVMModel___RigUnit_SetTranslation_Item__Const;   // 0x0028(0x000C)(Edit, EditConst, NonTransactional, NoDestructor, HasGetValueTypeHash)
	ERigVMTransformSpace                          RigVMModel___RigUnit_SetTranslation_Space__Const;  // 0x0034(0x0001)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          RigVMModel___RigUnit_SetTranslation_bInitial__Const; // 0x0035(0x0001)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36[0x2];                                       // 0x0036(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRigElementKey                         RigVMModel___RigUnit_GetTransform_Item__Const;     // 0x0038(0x000C)(Edit, EditConst, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         RigVMModel___RigUnit_GetTransform_1_Item__Const;   // 0x0044(0x000C)(Edit, EditConst, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___Interpolate_T__Const;                 // 0x0050(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___VerletIntegrateVector_Strength__Const; // 0x0054(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___VerletIntegrateVector_Damp__Const;    // 0x0058(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___VerletIntegrateVector_Blend__Const;   // 0x005C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FVector                                RigVMModel___VerletIntegrateVector_Force__Const;   // 0x0060(0x0018)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___RigUnit_SetTranslation_Weight__Const; // 0x0078(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         RigVMModel___AimItem_Item__Const;                  // 0x007C(0x000C)(Edit, EditConst, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FRigUnit_AimItem_Target                RigVMModel___AimItem_Primary__Const;               // 0x0088(0x0048)(Edit, EditConst, NonTransactional, NoDestructor)
	struct FRigUnit_AimItem_Target                RigVMModel___AimItem_Secondary__Const;             // 0x00D0(0x0048)(Edit, EditConst, NonTransactional, NoDestructor)
	uint8                                         Pad_118[0x8];                                      // 0x0118(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRigUnit_AimBone_DebugSettings         RigVMModel___AimItem_DebugSettings__Const;         // 0x0120(0x0070)(Edit, EditConst, NonTransactional, NoDestructor)
	struct FRigElementKey                         RigVMModel___AimItem_1_2_Item__Const;              // 0x0190(0x000C)(Edit, EditConst, NonTransactional, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19C[0x4];                                      // 0x019C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRigUnit_AimItem_Target                RigVMModel___AimItem_1_2_Secondary__Const;         // 0x01A0(0x0048)(Edit, EditConst, NonTransactional, NoDestructor)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL_FULLNAME("RigVMMemoryStorageGeneratorClass CR_SpiderWebShield.RigVMMemory_Literal")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RigVMMemory_Literal")
	}
	static class CR_SpiderWebShield::URigVMMemory_Literal* GetDefaultObj()
	{
		return GetDefaultObjImpl<CR_SpiderWebShield::URigVMMemory_Literal>();
	}
};
DUMPER7_ASSERTS_CR_SpiderWebShield__URigVMMemory_Literal;

SDK_NAMESPACE_END
