#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EState_VentilationHatch

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EState_VentilationHatch.EState_VentilationHatch
// NumValues: 0x0003
enum class EState_VentilationHatch : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	EState_MAX                               = 2,
};

SDK_NAMESPACE_END
