#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GlobalColorTheme_Frankenline

#include "Basic.hpp"

#include "GlobalColorTheme_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GlobalColorTheme_Frankenline.GlobalColorTheme_Frankenline_C
// 0x0000 (0x1DD8 - 0x1DD8)
class UGlobalColorTheme_Frankenline_C final : public UGlobalColorTheme_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GlobalColorTheme_Frankenline_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GlobalColorTheme_Frankenline_C")
	}
	static class UGlobalColorTheme_Frankenline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGlobalColorTheme_Frankenline_C>();
	}
};
DUMPER7_ASSERTS_UGlobalColorTheme_Frankenline_C;

SDK_NAMESPACE_END
