#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InGameMenuScreenType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum InGameMenuScreenType.InGameMenuScreenType
// NumValues: 0x000A
enum class EInGameMenuScreenType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator9                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator5                           = 5,
	NewEnumerator6                           = 6,
	NewEnumerator8                           = 7,
	NewEnumerator7                           = 8,
	InGameMenuScreenType_MAX                 = 9,
};

SDK_NAMESPACE_END
