#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Garden_SubjectV_Outro

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OEIFlowCharts_structs.hpp"
#include "LevelSequence_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LS_Garden_SubjectV_Outro.LS_Garden_SubjectV_Outro_DirectorBP_C
// 0x0038 (0x0080 - 0x0048)
class ULS_Garden_SubjectV_Outro_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0048(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FConversationReference                 Conversation;                                      // 0x0050(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FConversationReference                 PostFightConvo;                                    // 0x0068(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void CinLabOpen(class ABP_LDI_LabShutter_C* LabShutter);
	void cinLaserDeploy(class ABP_LDI_ArenaLab_Lasers_C* Lasers);
	void CinLaserRetract(class ABP_LDI_ArenaLab_Lasers_C* Lasers);
	void cinTreeVisible();
	void DefaultShutterOutro(class ABP_LDI_LabShutter_C* Lab_Shutter);
	void ExecuteUbergraph_LS_Garden_SubjectV_Outro_DirectorBP(int32 EntryPoint);
	void Play_CV_Garden_Bossfight_Outro(int32 NodeId);
	void Play_CV_Garden_Bossfight_Post();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_0();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_1();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_2();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_3();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_4();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_5();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_6();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_7();
	void SequenceEvent__ENTRYPOINTLS_Garden_SubjectV_Outro_DirectorBP_8();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LS_Garden_SubjectV_Outro_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LS_Garden_SubjectV_Outro_DirectorBP_C")
	}
	static class ULS_Garden_SubjectV_Outro_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULS_Garden_SubjectV_Outro_DirectorBP_C>();
	}
};
DUMPER7_ASSERTS_ULS_Garden_SubjectV_Outro_DirectorBP_C;

SDK_NAMESPACE_END
