#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_StatueLab_SubjectV_Intro

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OEIFlowCharts_structs.hpp"
#include "LevelSequence_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LS_StatueLab_SubjectV_Intro.LS_StatueLab_SubjectV_Intro_DirectorBP_C
// 0x0020 (0x0068 - 0x0048)
class ULS_StatueLab_SubjectV_Intro_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0048(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FConversationReference                 Conversation;                                      // 0x0050(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BP_LDI_Pushback_Event(class ABP_LDI_Pushback_C* BP_LDI_Pushback);
	void ExecuteUbergraph_LS_StatueLab_SubjectV_Intro_DirectorBP(int32 EntryPoint);
	void Play_cv_statue_bossfight_intro(int32 NodeId);
	void SequenceEvent__ENTRYPOINTLS_StatueLab_SubjectV_Intro_DirectorBP();
	void SequenceEvent__ENTRYPOINTLS_StatueLab_SubjectV_Intro_DirectorBP_0();
	void SequenceEvent__ENTRYPOINTLS_StatueLab_SubjectV_Intro_DirectorBP_1();
	void SequenceEvent__ENTRYPOINTLS_StatueLab_SubjectV_Intro_DirectorBP_2();
	void SequenceEvent__ENTRYPOINTLS_StatueLab_SubjectV_Intro_DirectorBP_3(class ABP_LDI_Pushback_C* BP_LDI_Pushback);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LS_StatueLab_SubjectV_Intro_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LS_StatueLab_SubjectV_Intro_DirectorBP_C")
	}
	static class ULS_StatueLab_SubjectV_Intro_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULS_StatueLab_SubjectV_Intro_DirectorBP_C>();
	}
};
DUMPER7_ASSERTS_ULS_StatueLab_SubjectV_Intro_DirectorBP_C;

SDK_NAMESPACE_END
