#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OEIAimAssist

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function OEIAimAssist.CameraModifier_AimAdhesion.GetCurrentAdhesionDistance
// 0x0004 (0x0004 - 0x0000)
struct CameraModifier_AimAdhesion_GetCurrentAdhesionDistance final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CameraModifier_AimAdhesion_GetCurrentAdhesionDistance;

// Function OEIAimAssist.CameraModifier_AimAdhesion.GetCurrentAdhesionPercent
// 0x0004 (0x0004 - 0x0000)
struct CameraModifier_AimAdhesion_GetCurrentAdhesionPercent final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CameraModifier_AimAdhesion_GetCurrentAdhesionPercent;

// Function OEIAimAssist.CameraModifier_AimAdhesion.GetCurrentAdhesionRadius
// 0x0004 (0x0004 - 0x0000)
struct CameraModifier_AimAdhesion_GetCurrentAdhesionRadius final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CameraModifier_AimAdhesion_GetCurrentAdhesionRadius;

// Function OEIAimAssist.AimAdhesionInterface.GetAdhesionPoint
// 0x0020 (0x0020 - 0x0000)
struct AimAdhesionInterface_GetAdhesionPoint final
{
public:
	struct FVector                                OutAdhesionPoint;                                  // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AimAdhesionInterface_GetAdhesionPoint;

// Function OEIAimAssist.AimAdhesionManager.Get
// 0x0010 (0x0010 - 0x0000)
struct AimAdhesionManager_Get final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAimAdhesionManager*                    ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AimAdhesionManager_Get;

// Function OEIAimAssist.AimAdhesionManager.RegisterActor
// 0x0010 (0x0010 - 0x0000)
struct AimAdhesionManager_RegisterActor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AimAdhesionManager_RegisterActor;

// Function OEIAimAssist.AimAdhesionManager.UnRegisterActor
// 0x0010 (0x0010 - 0x0000)
struct AimAdhesionManager_UnRegisterActor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AimAdhesionManager_UnRegisterActor;

// Function OEIAimAssist.AimAssistInterface.GetFindTargetTraceInfo
// 0x0038 (0x0038 - 0x0000)
struct AimAssistInterface_GetFindTargetTraceInfo final
{
public:
	struct FVector                                OutTraceOrigin;                                    // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                OutTraceDirection;                                 // 0x0018(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AimAssistInterface_GetFindTargetTraceInfo;

// Function OEIAimAssist.AimAssistInterface.IsTargetValid
// 0x0001 (0x0001 - 0x0000)
struct AimAssistInterface_IsTargetValid final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AimAssistInterface_IsTargetValid;

// Function OEIAimAssist.AimAssistSettings.Get
// 0x0008 (0x0008 - 0x0000)
struct AimAssistSettings_Get final
{
public:
	class UAimAssistSettings*                     ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AimAssistSettings_Get;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
