#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OEIVoiceOver

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MovieScene_structs.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// Enum OEIVoiceOver.EOEIEmotionLayer
// NumValues: 0x0004
enum class EOEIEmotionLayer : uint8
{
	Expression                               = 0,
	Paralingual                              = 1,
	Count                                    = 2,
	EOEIEmotionLayer_MAX                     = 3,
};

// Enum OEIVoiceOver.EOEINonVerbalDetection
// NumValues: 0x0005
enum class EOEINonVerbalDetection : uint8
{
	ProjectDefault                           = 0,
	NoDetection                              = 1,
	Detect                                   = 2,
	Count                                    = 3,
	EOEINonVerbalDetection_MAX               = 4,
};

// Enum OEIVoiceOver.EVoiceOverAudioImplementationType
// NumValues: 0x0007
enum class EVoiceOverAudioImplementationType : uint8
{
	Default                                  = 0,
	FaceFX                                   = 1,
	FaceFXExternalAudio                      = 2,
	CurveTables                              = 3,
	CurveTablesUnrealAudio                   = 4,
	CurveTablesOEIWwise                      = 5,
	EVoiceOverAudioImplementationType_MAX    = 6,
};

// Enum OEIVoiceOver.EVoiceOverEmotionFormat
// NumValues: 0x0003
enum class EVoiceOverEmotionFormat : uint8
{
	JALI                                     = 0,
	FaceFX                                   = 1,
	EVoiceOverEmotionFormat_MAX              = 2,
};

// ScriptStruct OEIVoiceOver.VoiceOverData
// 0x0060 (0x0060 - 0x0000)
struct FVoiceOverData final
{
public:
	class FName                                   AudioEventType;                                    // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UObject>                 AudioPath;                                         // 0x0008(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UObject>                 AnimationPath;                                     // 0x0030(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsChatter;                                        // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsSoundEffect;                                    // 0x0059(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5A[0x6];                                       // 0x005A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FVoiceOverData;

// ScriptStruct OEIVoiceOver.AnimNode_OEIBlendFaceFXAnimation
// 0x0048 (0x0058 - 0x0010)
struct FAnimNode_OEIBlendFaceFXAnimation final : public FAnimNode_Base
{
public:
	struct FComponentSpacePoseLink                ComponentPose;                                     // 0x0010(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         Alpha;                                             // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSkipBoneMappingWithoutNS;                         // 0x0024(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LODThreshold;                                      // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x2C];                                      // 0x002C(0x002C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAnimNode_OEIBlendFaceFXAnimation;

// ScriptStruct OEIVoiceOver.AnimNode_OEIBlendFaceFXCurves
// 0x0030 (0x0040 - 0x0010)
struct FAnimNode_OEIBlendFaceFXCurves final : public FAnimNode_Base
{
public:
	struct FComponentSpacePoseLink                ComponentPose;                                     // 0x0010(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	class UPoseAsset*                             PoseAsset;                                         // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	float                                         Alpha;                                             // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSkipBoneMappingWithoutNS;                         // 0x002C(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LODThreshold;                                      // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0xC];                                       // 0x0034(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAnimNode_OEIBlendFaceFXCurves;

// ScriptStruct OEIVoiceOver.AnimNode_OEICurveSource
// 0x0078 (0x0088 - 0x0010)
struct FAnimNode_OEICurveSource final : public FAnimNode_Base
{
public:
	struct FPoseLink                              SourcePose;                                        // 0x0010(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         Alpha;                                             // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOEIVoiceOverCurveRegions*              CurveRegions;                                      // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	int32                                         LODThreshold;                                      // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x54];                                      // 0x0034(0x0054)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAnimNode_OEICurveSource;

// ScriptStruct OEIVoiceOver.AnimNode_OEIEmotionBlend
// 0x0058 (0x0068 - 0x0010)
struct FAnimNode_OEIEmotionBlend final : public FAnimNode_Base
{
public:
	struct FPoseLink                              BasePose;                                          // 0x0010(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	struct FPoseLink                              BlendPose;                                         // 0x0020(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         BlendWeight;                                       // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           FullWeightCurveNames;                              // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         FullWeightCurveMultiplier;                         // 0x0048(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LODThreshold;                                      // 0x004C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x18];                                      // 0x0050(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAnimNode_OEIEmotionBlend;

// ScriptStruct OEIVoiceOver.AnimNode_OEIJaliFixer
// 0x0048 (0x0058 - 0x0010)
struct FAnimNode_OEIJaliFixer final : public FAnimNode_Base
{
public:
	struct FPoseLink                              SourcePose;                                        // 0x0010(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         Alpha;                                             // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x34];                                      // 0x0024(0x0034)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAnimNode_OEIJaliFixer;

// ScriptStruct OEIVoiceOver.AnimNode_OEIPlayCurveTable
// 0x0040 (0x0050 - 0x0010)
struct FAnimNode_OEIPlayCurveTable final : public FAnimNode_Base
{
public:
	struct FPoseLink                              SourcePose;                                        // 0x0010(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         Strength;                                          // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Alpha;                                             // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveForAlpha;                                     // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          InverseAlpha;                                      // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveTable*                            CurveTable;                                        // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	bool                                          Loop;                                              // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0xF];                                       // 0x0041(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAnimNode_OEIPlayCurveTable;

// ScriptStruct OEIVoiceOver.OEIVOEmotionSectionParams
// 0x0128 (0x0128 - 0x0000)
struct FOEIVOEmotionSectionParams final
{
public:
	struct FGameplayTag                           Emotion;                                           // 0x0000(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Weight;                                            // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneFloatChannel                KeyedWeight;                                       // 0x0010(0x0110)(NativeAccessSpecifierPublic)
	bool                                          Persist;                                           // 0x0120(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FOEIVOEmotionSectionParams;

// ScriptStruct OEIVoiceOver.OEIVOEmotionExpressionSectionTemplate
// 0x0128 (0x0148 - 0x0020)
struct FOEIVOEmotionExpressionSectionTemplate final : public FMovieSceneEvalTemplate
{
public:
	struct FOEIVOEmotionSectionParams             Params;                                            // 0x0020(0x0128)(NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FOEIVOEmotionExpressionSectionTemplate;

// ScriptStruct OEIVoiceOver.OEIVOEmotionParalingualSectionTemplate
// 0x0128 (0x0148 - 0x0020)
struct FOEIVOEmotionParalingualSectionTemplate final : public FMovieSceneEvalTemplate
{
public:
	struct FOEIVOEmotionSectionParams             Params;                                            // 0x0020(0x0128)(NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FOEIVOEmotionParalingualSectionTemplate;

// ScriptStruct OEIVoiceOver.OEIVOEmotionSectionTemplate
// 0x0128 (0x0148 - 0x0020)
struct FOEIVOEmotionSectionTemplate final : public FMovieSceneEvalTemplate
{
public:
	struct FOEIVOEmotionSectionParams             Params;                                            // 0x0020(0x0128)(NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FOEIVOEmotionSectionTemplate;

// ScriptStruct OEIVoiceOver.VoiceOverComponentSetupData
// 0x0018 (0x0018 - 0x0000)
struct FVoiceOverComponentSetupData final
{
public:
	class FName                                   AudioAttachmentSocketName;                         // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                FaceFXActor;                                       // 0x0008(0x0008)(Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	bool                                          bCompensateForForceFrontXAxis;                     // 0x0010(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoPlaySound;                                    // 0x0011(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDisableMorphTargets;                              // 0x0012(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDisableMaterialParameters;                        // 0x0013(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FVoiceOverComponentSetupData;

// ScriptStruct OEIVoiceOver.OEIVoiceOverCurveInfluence
// 0x000C (0x000C - 0x0000)
struct FOEIVoiceOverCurveInfluence final
{
public:
	class FName                                   Name;                                              // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Influence;                                         // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FOEIVoiceOverCurveInfluence;

// ScriptStruct OEIVoiceOver.OEIVoiceOverCurveRegion
// 0x0018 (0x0018 - 0x0000)
struct FOEIVoiceOverCurveRegion final
{
public:
	class FName                                   ControlCurve;                                      // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FOEIVoiceOverCurveInfluence>    RegionCurves;                                      // 0x0008(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FOEIVoiceOverCurveRegion;

// ScriptStruct OEIVoiceOver.OEIVoiceOverLineEmphasisDetails
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) FOEIVoiceOverLineEmphasisDetails final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FOEIVoiceOverLineEmphasisDetails;

// ScriptStruct OEIVoiceOver.OEIVoiceOverPhoneme
// 0x0048 (0x0048 - 0x0000)
struct alignas(0x08) FOEIVoiceOverPhoneme final
{
public:
	uint8                                         Pad_0[0x48];                                       // 0x0000(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FOEIVoiceOverPhoneme;

// ScriptStruct OEIVoiceOver.OEIVoiceOverWord
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x04) FOEIVoiceOverWord final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FOEIVoiceOverWord;

// ScriptStruct OEIVoiceOver.OEIVoiceOverPhonemeCollection
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FOEIVoiceOverPhonemeCollection final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FOEIVoiceOverPhonemeCollection;

// ScriptStruct OEIVoiceOver.OEIVoiceOverSectionTemplate
// 0x0008 (0x0028 - 0x0020)
struct FOEIVoiceOverSectionTemplate final : public FMovieSceneEvalTemplate
{
public:
	class UOEIVoiceOverSection*                   Section;                                           // 0x0020(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
};
DUMPER7_ASSERTS_FOEIVoiceOverSectionTemplate;

// ScriptStruct OEIVoiceOver.OEIVoiceOverUtils
// 0x0001 (0x0001 - 0x0000)
struct FOEIVoiceOverUtils final
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FOEIVoiceOverUtils;

SDK_NAMESPACE_END
