#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SG_PickerelFlowers

#include "Basic.hpp"

#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SG_PickerelFlowers.SG_PickerelFlowers_C
// 0x0000 (0x0070 - 0x0070)
class USG_PickerelFlowers_C final : public UItemSpawnGroupData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SG_PickerelFlowers_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SG_PickerelFlowers_C")
	}
	static class USG_PickerelFlowers_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USG_PickerelFlowers_C>();
	}
};
DUMPER7_ASSERTS_USG_PickerelFlowers_C;

SDK_NAMESPACE_END
