#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Buttons_Playgrounds

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_Buttons_Playgrounds.UI_Buttons_Playgrounds_C
// 0x0050 (0x03D0 - 0x0380)
class UUI_Buttons_Playgrounds_C final : public UMainMenuButtonsGroup
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_MainMenuButton_C*                   ButtonSinglePlayer;                                // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_MainMenuButton_C*                   ButtonMultiplayer;                                 // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_MainMenuButton_C*                   ButtonBack;                                        // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnSinglePlayerClicked;                             // 0x03A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnMultiplayerClicked;                              // 0x03B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnBackClicked;                                     // 0x03C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__UI_Buttons_HostJoin_ButtonHostGame_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature();
	void BndEvt__UI_Buttons_HostJoin_ButtonHostJoinBack_K2Node_ComponentBoundEvent_2_OnButtonClicked__DelegateSignature();
	void BndEvt__UI_Buttons_HostJoin_ButtonJoinGame_K2Node_ComponentBoundEvent_1_OnButtonClicked__DelegateSignature();
	void ExecuteUbergraph_UI_Buttons_Playgrounds(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Buttons_Playgrounds_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Buttons_Playgrounds_C")
	}
	static class UUI_Buttons_Playgrounds_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Buttons_Playgrounds_C>();
	}
};
DUMPER7_ASSERTS_UUI_Buttons_Playgrounds_C;

SDK_NAMESPACE_END
