#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_BuildingRadialMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OEIText_structs.hpp"
#include "Maine_structs.hpp"
#include "UMG_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "UI_RadialMenu_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_BuildingRadialMenu.UI_BuildingRadialMenu_C
// 0x0090 (0x06F0 - 0x0660)
class UUI_BuildingRadialMenu_C : public UUI_RadialMenu_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_UI_BuildingRadialMenu_C;            // 0x0660(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTag                           CurrentBuildingCategory;                           // 0x0668(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<struct FDataTableRowHandle>            BuildingRecipesForCategory;                        // 0x0670(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FGameplayTag>                   AvailableCategories;                               // 0x0680(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FLocString                             EnterBuildMode;                                    // 0x0690(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FLocString                             ExitBuildMode;                                     // 0x06A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<struct FGameplayTag>                   EditModeOnlyCategories;                            // 0x06B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FBuildingRecipeData>            BuildRecipeDataArray;                              // 0x06C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FGameplayTag>                   ValidBuildingCategories;                           // 0x06D0(0x0010)(Edit, BlueprintVisible)
	class UDataTable*                             MetaBuildingTable;                                 // 0x06E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowLocked;                                        // 0x06E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void CalculateValidBuildingCategories();
	void CheckBroadcastCombatState();
	void Construct();
	void Destruct();
	void ExecuteUbergraph_UI_BuildingRadialMenu(int32 EntryPoint);
	void Get_Known_and_Sorted_Building_Recipes_for_Category(const struct FGameplayTag& BuildingCategory, TArray<struct FDataTableRowHandle>* KnownBuildingRecipes);
	void GetBuildingRecipeCategoryTag(const struct FDataTableRowHandle& BuildingRecipe, struct FGameplayTag* CategoryTag);
	void GetBuildingRecipeForAnyHandle(const struct FDataTableRowHandle& Handle, struct FDataTableRowHandle* BuildingRecipe);
	void GetCategoryCount(int32* Count);
	void GetCategoryHeader_0(const struct FGameplayTag& Category, class UUI_BuildingRadialHeaderButton_C** CategoryHeader);
	void GetCategoryIcon(int32 Category, class UTexture2D** Texture);
	void GetCategoryTitle(int32 Category, class FName* CategoryString);
	struct FLinearColor GetDescColor();
	void GetKnownBuildingRecipesForCategory(const struct FGameplayTag& BuildingCategory, TArray<struct FDataTableRowHandle>* KnownBuildingRecipes);
	int32 GetMetaBuildingCurrentSubBuildingIndex(const struct FDataTableRowHandle& MetabuildingRow);
	int32 GetMetaBuildingUnlockedSubBuildingNum(const struct FDataTableRowHandle& MetaBuilding);
	void GetNextCategory(const struct FGameplayTag& CurrentCategory, struct FGameplayTag* Category);
	void GetPageCountForBuildingCategory(const struct FGameplayTag& Category, int32* Count);
	void GetPageCountForCategory(int32 CategoryIndex, int32* Count);
	struct FLinearColor GetRadialBGColor();
	void GotoNextBuildingMaterial();
	void GotoPreviousBuildingMaterial();
	void HandleCategoryChange(int32 PreviousCategoryIndex);
	void HandleHoverSlot();
	void HandleNextVariant();
	void HandlePreviousVariant();
	void HandleSelectLastRecipe();
	void HandleUseSlot(bool* CloseOnUse);
	void OnBuildModeChangedEvent(class APlayerController* PlayerController, bool IsInBuildMode);
	void OnGlobalColorChange();
	void Populate();
	void PopulateBuildingCategories();
	void PopulateCategories();
	void PreloadData();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_BuildingRadialMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_BuildingRadialMenu_C")
	}
	static class UUI_BuildingRadialMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_BuildingRadialMenu_C>();
	}
};
DUMPER7_ASSERTS_UUI_BuildingRadialMenu_C;

SDK_NAMESPACE_END
