#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_BindKeyConfirmPopUp

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Slate_structs.hpp"
#include "Maine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_BindKeyConfirmPopUp.UI_BindKeyConfirmPopUp_C.EventLargeFonts
// 0x0001 (0x0001 - 0x0000)
struct UI_BindKeyConfirmPopUp_C_EventLargeFonts final
{
public:
	bool                                          NewValue;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_BindKeyConfirmPopUp_C_EventLargeFonts;

// Function UI_BindKeyConfirmPopUp.UI_BindKeyConfirmPopUp_C.ExecuteUbergraph_UI_BindKeyConfirmPopUp
// 0x0048 (0x0048 - 0x0000)
struct UI_BindKeyConfirmPopUp_C_ExecuteUbergraph_UI_BindKeyConfirmPopUp final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetManager*                         CallFunc_GetWidgetManager_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPauseMenuActive_ReturnValue;            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaineGameUserSettings*                 CallFunc_K2_GetMaineGameUserSettings_ReturnValue;  // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_NewValue;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool NewValue)>                K2Node_CreateDelegate_OutputDelegate;              // 0x0024(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USurvivalGameInstance*                  CallFunc_GetSurvivalGameInstance_ReturnValue;      // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCurrentLevelMenuLevel_ReturnValue;      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_BindKeyConfirmPopUp_C_ExecuteUbergraph_UI_BindKeyConfirmPopUp;

// Function UI_BindKeyConfirmPopUp.UI_BindKeyConfirmPopUp_C.HandleKeyEventChord
// 0x0028 (0x0028 - 0x0000)
struct UI_BindKeyConfirmPopUp_C_HandleKeyEventChord final
{
public:
	struct FInputChord                            InChord;                                           // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DoesChordMatchActionMapping_ReturnValue;  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DoesChordMatchActionMapping_ReturnValue_1; // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HandleKeyEventChord_ReturnValue;          // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_BindKeyConfirmPopUp_C_HandleKeyEventChord;

// Function UI_BindKeyConfirmPopUp.UI_BindKeyConfirmPopUp_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_BindKeyConfirmPopUp_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_BindKeyConfirmPopUp_C_PreConstruct;

// Function UI_BindKeyConfirmPopUp.UI_BindKeyConfirmPopUp_C.RefreshColors
// 0x00FC (0x00FC - 0x0000)
struct UI_BindKeyConfirmPopUp_C_RefreshColors final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0014(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_1;             // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_1;              // 0x0038(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_2;             // 0x004C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_2;              // 0x005C(0x0014)()
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0070(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_3;             // 0x0080(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_3;              // 0x0090(0x0014)()
	struct FLinearColor                           K2Node_Select_Default_1;                           // 0x00A4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_4;             // 0x00B4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_4;              // 0x00C4(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_5;             // 0x00D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_5;              // 0x00E8(0x0014)()
};
DUMPER7_ASSERTS_UI_BindKeyConfirmPopUp_C_RefreshColors;

// Function UI_BindKeyConfirmPopUp.UI_BindKeyConfirmPopUp_C.SetInstructionText
// 0x0058 (0x0058 - 0x0000)
struct UI_BindKeyConfirmPopUp_C_SetInstructionText final
{
public:
	class FString                                 Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	struct FAnyControlMapping                     InputChord;                                        // 0x0010(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          bRebindable_0;                                     // 0x0040(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0048(0x0010)()
};
DUMPER7_ASSERTS_UI_BindKeyConfirmPopUp_C_SetInstructionText;

// Function UI_BindKeyConfirmPopUp.UI_BindKeyConfirmPopUp_C.SetLargeFont
// 0x00F0 (0x00F0 - 0x0000)
struct UI_BindKeyConfirmPopUp_C_SetLargeFont final
{
public:
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue_1;             // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0018(0x0060)(HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo_1;                 // 0x0078(0x0060)(HasGetValueTypeHash)
	class UMaineGameUserSettings*                 CallFunc_K2_GetMaineGameUserSettings_ReturnValue;  // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLargeText_ReturnValue;                 // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E2[0x2];                                       // 0x00E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_MakeStruct_Size_ImplicitCast;               // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_Size_ImplicitCast_1;             // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_BindKeyConfirmPopUp_C_SetLargeFont;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
