#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ConnectedStorageInfo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_ConnectedStorageInfo.UI_ConnectedStorageInfo_C
// 0x0040 (0x03B8 - 0x0378)
class UUI_ConnectedStorageInfo_C final : public UGameUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UGameTextBlock*                         NumberText;                                        // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Container;                                         // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizedTextBlock*                    ConnectedTextBlock;                                // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizedTextBlock*                    ConnectedExclamation;                              // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_0;                                          // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProximityInventoryComponent*           ProximityInventoryComponent;                       // 0x03A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bForceLargeFont;                                   // 0x03B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsASL;                                             // 0x03B1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetLargeFont();
	void Construct();
	void OnGlobalColorChange();
	void ReevaluateNearbyStorage();
	void SetProximityInventoryComponent(class UProximityInventoryComponent* ProximityInventoryComponent_0);
	void Destruct();
	void BindPlayerEvents(class ASurvivalPlayerCharacter* Player);
	void UnbindPlayerEvents(class ASurvivalPlayerCharacter* Player);
	void OnProximityInventotyChanged();
	void EventLargeFonts(bool NewValue);
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_UI_ConnectedStorageInfo(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_ConnectedStorageInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_ConnectedStorageInfo_C")
	}
	static class UUI_ConnectedStorageInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ConnectedStorageInfo_C>();
	}
};
DUMPER7_ASSERTS_UUI_ConnectedStorageInfo_C;

SDK_NAMESPACE_END
