#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ClockSmall

#include "Basic.hpp"

#include "UI_ClockSmall_classes.hpp"
#include "UI_ClockSmall_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_ClockSmall.UI_ClockSmall_C.SetLargeFont
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_ClockSmall_C::SetLargeFont()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "SetLargeFont");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ClockSmall.UI_ClockSmall_C.DisplayGameTime
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_ClockSmall_C::DisplayGameTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "DisplayGameTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ClockSmall.UI_ClockSmall_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_ClockSmall_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ClockSmall.UI_ClockSmall_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ClockSmall_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "Tick");

	Params::UI_ClockSmall_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ClockSmall.UI_ClockSmall_C.OnGlobalColorChange
// (Event, Protected, BlueprintEvent)

void UUI_ClockSmall_C::OnGlobalColorChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "OnGlobalColorChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ClockSmall.UI_ClockSmall_C.EventLargeFonts
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ClockSmall_C::EventLargeFonts(bool NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "EventLargeFonts");

	Params::UI_ClockSmall_C_EventLargeFonts Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ClockSmall.UI_ClockSmall_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_ClockSmall_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ClockSmall.UI_ClockSmall_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ClockSmall_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "PreConstruct");

	Params::UI_ClockSmall_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ClockSmall.UI_ClockSmall_C.ExecuteUbergraph_UI_ClockSmall
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ClockSmall_C::ExecuteUbergraph_UI_ClockSmall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ClockSmall_C", "ExecuteUbergraph_UI_ClockSmall");

	Params::UI_ClockSmall_C_ExecuteUbergraph_UI_ClockSmall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
