#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_HotBarRadialMenu

#include "Basic.hpp"

#include "UI_HotBarRadialMenu_classes.hpp"
#include "UI_HotBarRadialMenu_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.IsInAssignMode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   IsDragging                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::IsInAssignMode(bool* IsDragging)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "IsInAssignMode");

	Params::UI_HotBarRadialMenu_C_IsInAssignMode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsDragging != nullptr)
		*IsDragging = Parms.IsDragging;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.OnHoldUnassignNotCompleted
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::OnHoldUnassignNotCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "OnHoldUnassignNotCompleted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.HandleNextVariant
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::HandleNextVariant()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "HandleNextVariant");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.HandlePreviousVariant
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::HandlePreviousVariant()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "HandlePreviousVariant");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.UpdateDefaultCenterText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::UpdateDefaultCenterText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "UpdateDefaultCenterText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUI_HotBarRadialMenu_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "OnKeyUp");

	Params::UI_HotBarRadialMenu_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUI_HotBarRadialMenu_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "OnKeyDown");

	Params::UI_HotBarRadialMenu_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.UpdateUnassignButton
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::UpdateUnassignButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "UpdateUnassignButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.UpdateRadialArrow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::UpdateRadialArrow(class UObject* Item, int32 SlotIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "UpdateRadialArrow");

	Params::UI_HotBarRadialMenu_C_UpdateRadialArrow Parms{};

	Parms.Item = Item;
	Parms.SlotIndex = SlotIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.OnAnalogValueChanged
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FAnalogInputEvent&         InAnalogInputEvent                                     (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUI_HotBarRadialMenu_C::OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "OnAnalogValueChanged");

	Params::UI_HotBarRadialMenu_C_OnAnalogValueChanged Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InAnalogInputEvent = std::move(InAnalogInputEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.HandleKeyEventChord
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FInputChord&               InChord                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UUI_HotBarRadialMenu_C::HandleKeyEventChord(const struct FInputChord& InChord)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "HandleKeyEventChord");

	Params::UI_HotBarRadialMenu_C_HandleKeyEventChord Parms{};

	Parms.InChord = std::move(InChord);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.OnUnassignAction
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::OnUnassignAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "OnUnassignAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.CanUnassign
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   CanUnassign_0                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::CanUnassign(bool* CanUnassign_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "CanUnassign");

	Params::UI_HotBarRadialMenu_C_CanUnassign Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanUnassign_0 != nullptr)
		*CanUnassign_0 = Parms.CanUnassign_0;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.HandleHoverSlot
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::HandleHoverSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "HandleHoverSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.HandleUseSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   CloseOnUse                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::HandleUseSlot(bool* CloseOnUse)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "HandleUseSlot");

	Params::UI_HotBarRadialMenu_C_HandleUseSlot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CloseOnUse != nullptr)
		*CloseOnUse = Parms.CloseOnUse;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.PreviousPage
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::PreviousPage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "PreviousPage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.NextPage
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::NextPage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "NextPage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.GetHeaderText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   page                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    AppendRadialName                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            Text                                                   (Parm, OutParm)

void UUI_HotBarRadialMenu_C::GetHeaderText(int32 page, bool AppendRadialName, class FText* Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "GetHeaderText");

	Params::UI_HotBarRadialMenu_C_GetHeaderText Parms{};

	Parms.page = page;
	Parms.AppendRadialName = AppendRadialName;

	UObject::ProcessEvent(Func, &Parms);

	if (Text != nullptr)
		*Text = std::move(Parms.Text);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.GetCategoryIcon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D**                      Texture                                                (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::GetCategoryIcon(int32 Category, class UTexture2D** Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "GetCategoryIcon");

	Params::UI_HotBarRadialMenu_C_GetCategoryIcon Parms{};

	Parms.Category = Category;

	UObject::ProcessEvent(Func, &Parms);

	if (Texture != nullptr)
		*Texture = Parms.Texture;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.GetDescColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_HotBarRadialMenu_C::GetDescColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "GetDescColor");

	Params::UI_HotBarRadialMenu_C_GetDescColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.GetPageCountForCategory
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   CategoryIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Count                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::GetPageCountForCategory(int32 CategoryIndex, int32* Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "GetPageCountForCategory");

	Params::UI_HotBarRadialMenu_C_GetPageCountForCategory Parms{};

	Parms.CategoryIndex = CategoryIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (Count != nullptr)
		*Count = Parms.Count;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.GetCategoryCount
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  Count                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::GetCategoryCount(int32* Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "GetCategoryCount");

	Params::UI_HotBarRadialMenu_C_GetCategoryCount Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Count != nullptr)
		*Count = Parms.Count;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.GetRadialBGColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_HotBarRadialMenu_C::GetRadialBGColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "GetRadialBGColor");

	Params::UI_HotBarRadialMenu_C_GetRadialBGColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_HotBarRadialMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.Populate
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::Populate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "Populate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "Tick");

	Params::UI_HotBarRadialMenu_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.PopulateCategories
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::PopulateCategories()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "PopulateCategories");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.HandleSelectLastItem
// (BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::HandleSelectLastItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "HandleSelectLastItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.OnInventoryChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UInventoryComponent*              Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::OnInventoryChanged(class UInventoryComponent* Sender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "OnInventoryChanged");

	Params::UI_HotBarRadialMenu_C_OnInventoryChanged Parms{};

	Parms.Sender = Sender;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_HotBarRadialMenu_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.Handle Equipment Changed
// (BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::Handle_Equipment_Changed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "Handle Equipment Changed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.OnUsingGamepadChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bOnUsingGamepadChanged                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::OnUsingGamepadChanged(bool bOnUsingGamepadChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "OnUsingGamepadChanged");

	Params::UI_HotBarRadialMenu_C_OnUsingGamepadChanged Parms{};

	Parms.bOnUsingGamepadChanged = bOnUsingGamepadChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.OnSelectedIconImageLoaded
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           LoadedIcon                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::OnSelectedIconImageLoaded(class UImage* LoadedIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "OnSelectedIconImageLoaded");

	Params::UI_HotBarRadialMenu_C_OnSelectedIconImageLoaded Parms{};

	Parms.LoadedIcon = LoadedIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.UpdateCenterWidget
// (BlueprintCallable, BlueprintEvent)

void UUI_HotBarRadialMenu_C::UpdateCenterWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "UpdateCenterWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HotBarRadialMenu.UI_HotBarRadialMenu_C.ExecuteUbergraph_UI_HotBarRadialMenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HotBarRadialMenu_C::ExecuteUbergraph_UI_HotBarRadialMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HotBarRadialMenu_C", "ExecuteUbergraph_UI_HotBarRadialMenu");

	Params::UI_HotBarRadialMenu_C_ExecuteUbergraph_UI_HotBarRadialMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
