#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_LoggedInUserName

#include "Basic.hpp"

#include "OEIText_structs.hpp"
#include "InterfaceNarration_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_LoggedInUserName.UI_LoggedInUserName_C.ExecuteUbergraph_UI_LoggedInUserName
// 0x0028 (0x0028 - 0x0000)
struct UI_LoggedInUserName_C_ExecuteUbergraph_UI_LoggedInUserName final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0014(0x0014)()
};
DUMPER7_ASSERTS_UI_LoggedInUserName_C_ExecuteUbergraph_UI_LoggedInUserName;

// Function UI_LoggedInUserName.UI_LoggedInUserName_C.GetNarration
// 0x00E0 (0x00E0 - 0x0000)
struct UI_LoggedInUserName_C_GetNarration final
{
public:
	TArray<struct FNarrationChunk>                Chunks;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          bVerbose;                                          // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLocString                             LoggedInFormatString;                              // 0x0014(0x0010)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0028(0x0010)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0048)(HasGetValueTypeHash)
	class FString                                 CallFunc_GetLocStringText_ReturnValue;             // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0090(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00A0(0x0010)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00B0(0x0010)()
	struct FNarrationChunk                        CallFunc_AddNarrationChunk_ReturnValue;            // 0x00C0(0x0020)()
};
DUMPER7_ASSERTS_UI_LoggedInUserName_C_GetNarration;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
