#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MassiveBottomButton

#include "Basic.hpp"

#include "ConfirmationButtonConfig_structs.hpp"
#include "SlateCore_structs.hpp"
#include "InterfaceNarration_structs.hpp"
#include "OEIText_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.EventLargeFonts
// 0x0001 (0x0001 - 0x0000)
struct UI_MassiveBottomButton_C_EventLargeFonts final
{
public:
	bool                                          NewValue;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_EventLargeFonts;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.ExecuteUbergraph_UI_MassiveBottomButton
// 0x00A0 (0x00A0 - 0x0000)
struct UI_MassiveBottomButton_C_ExecuteUbergraph_UI_MassiveBottomButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextBlock*                             CallFunc_SetEnabledStyle_TextElement;              // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                CallFunc_SetEnabledStyle_ButtonInner;              // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             CallFunc_SetDisabledStyle_TextElement;             // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                CallFunc_SetDisabledStyle_ButtonInner;             // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bEnabled;                             // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bOnUsingGamepadChanged;               // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextBlock*                             CallFunc_SetDownState_TextElement;                 // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                CallFunc_SetDownState_ButtonInner;                 // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_InFocusEvent_1;                       // 0x0048(0x0008)(NoDestructor)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x0050(0x0008)(NoDestructor)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0058(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_1;              // 0x0068(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaineGameUserSettings*                 CallFunc_K2_GetMaineGameUserSettings_ReturnValue;  // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_NewValue;                       // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool NewValue)>                K2Node_CreateDelegate_OutputDelegate;              // 0x008C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_ExecuteUbergraph_UI_MassiveBottomButton;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.NormalButtonHover
// 0x0058 (0x0058 - 0x0000)
struct UI_MassiveBottomButton_C_NormalButtonHover final
{
public:
	class APlayerController*                      self2;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0008(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x001C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x002C(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0040(0x0014)()
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_NormalButtonHover;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.NormalButtonUnhover
// 0x0040 (0x0040 - 0x0000)
struct UI_MassiveBottomButton_C_NormalButtonUnhover final
{
public:
	class APlayerController*                      self2;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0018(0x0014)()
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextBlock*                             CallFunc_SetDisabledStyle_TextElement;             // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                CallFunc_SetDisabledStyle_ButtonInner;             // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_NormalButtonUnhover;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct UI_MassiveBottomButton_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_OnAddedToFocusPath;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct UI_MassiveBottomButton_C_OnRemovedFromFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_OnRemovedFromFocusPath;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.OnSetIsValid
// 0x0001 (0x0001 - 0x0000)
struct UI_MassiveBottomButton_C_OnSetIsValid final
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_OnSetIsValid;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.OnUsingGamepadChanged
// 0x0001 (0x0001 - 0x0000)
struct UI_MassiveBottomButton_C_OnUsingGamepadChanged final
{
public:
	bool                                          bOnUsingGamepadChanged;                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_OnUsingGamepadChanged;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_MassiveBottomButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_PreConstruct;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.SetAbledness
// 0x0020 (0x0020 - 0x0000)
struct UI_MassiveBottomButton_C_SetAbledness final
{
public:
	class UTextBlock*                             CallFunc_SetDisabledStyle_TextElement;             // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                CallFunc_SetDisabledStyle_ButtonInner;             // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             CallFunc_SetEnabledStyle_TextElement;              // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                CallFunc_SetEnabledStyle_ButtonInner;              // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_SetAbledness;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.SetButtonConfig
// 0x0018 (0x0018 - 0x0000)
struct UI_MassiveBottomButton_C_SetButtonConfig final
{
public:
	struct FConfirmationButtonConfig              Config;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_SetButtonConfig;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.SetDisabledStyle
// 0x0060 (0x0060 - 0x0000)
struct UI_MassiveBottomButton_C_SetDisabledStyle final
{
public:
	class UTextBlock*                             TextElement;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                ButtonInner_0;                                     // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0010(0x0014)()
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue;           // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0038(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x004C(0x0014)()
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_SetDisabledStyle;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.SetDownState
// 0x00A8 (0x00A8 - 0x0000)
struct UI_MassiveBottomButton_C_SetDownState final
{
public:
	class UTextBlock*                             TextElement;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                ButtonInner_0;                                     // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0020(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_1;             // 0x0034(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_1;              // 0x0044(0x0014)()
	bool                                          CallFunc_ShouldShowHintOnly_Result;                // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_2;             // 0x005C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_2;              // 0x006C(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_3;             // 0x0080(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_3;              // 0x0090(0x0014)()
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_SetDownState;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.SetEnabledStyle
// 0x0080 (0x0080 - 0x0000)
struct UI_MassiveBottomButton_C_SetEnabledStyle final
{
public:
	class UTextBlock*                             TextElement;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UButton*                                ButtonInner_0;                                     // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0020(0x0014)()
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue;           // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0038(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_1;             // 0x0048(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_1;              // 0x0058(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x006C(0x0014)()
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_SetEnabledStyle;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.SetInputName
// 0x0008 (0x0008 - 0x0000)
struct UI_MassiveBottomButton_C_SetInputName final
{
public:
	class FName                                   InputName_0;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_SetInputName;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.SetLargeFont
// 0x00F0 (0x00F0 - 0x0000)
struct UI_MassiveBottomButton_C_SetLargeFont final
{
public:
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue_1;             // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0018(0x0060)(HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo_1;                 // 0x0078(0x0060)(HasGetValueTypeHash)
	class UMaineGameUserSettings*                 CallFunc_K2_GetMaineGameUserSettings_ReturnValue;  // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLargeText_ReturnValue;                 // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E2[0x2];                                       // 0x00E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_MakeStruct_Size_ImplicitCast;               // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_Size_ImplicitCast_1;             // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_SetLargeFont;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.SetLocalizedButtonText
// 0x0010 (0x0010 - 0x0000)
struct UI_MassiveBottomButton_C_SetLocalizedButtonText final
{
public:
	struct FLocString                             String;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_SetLocalizedButtonText;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.ShouldShowHintOnly
// 0x0003 (0x0003 - 0x0000)
struct UI_MassiveBottomButton_C_ShouldShowHintOnly final
{
public:
	bool                                          Result;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUsingGamepadControls_ReturnValue;       // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_ShouldShowHintOnly;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.GetIsValid
// 0x0001 (0x0001 - 0x0000)
struct UI_MassiveBottomButton_C_GetIsValid final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_GetIsValid;

// Function UI_MassiveBottomButton.UI_MassiveBottomButton_C.GetNarration
// 0x00A0 (0x00A0 - 0x0000)
struct UI_MassiveBottomButton_C_GetNarration final
{
public:
	TArray<struct FNarrationChunk>                Chunks;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          bVerbose;                                          // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLocString                             CallFunc_MakeLocString_ReturnValue;                // 0x0014(0x0010)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FNarrationChunk                        CallFunc_AddNarrationChunkLocString_ReturnValue;   // 0x0028(0x0020)()
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_NameName_ReturnValue;            // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0050(0x0010)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_1;                    // 0x0070(0x0010)()
	struct FNarrationChunk                        CallFunc_AddNarrationChunk_ReturnValue;            // 0x0080(0x0020)()
};
DUMPER7_ASSERTS_UI_MassiveBottomButton_C_GetNarration;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
