#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MapResourceSurveyOverlay

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_MapResourceSurveyOverlay.UI_MapResourceSurveyOverlay_C.ExecuteUbergraph_UI_MapResourceSurveyOverlay
// 0x0108 (0x0108 - 0x0000)
struct UI_MapResourceSurveyOverlay_C_ExecuteUbergraph_UI_MapResourceSurveyOverlay final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class ASurvivalPlayerState* Sender, bool bValue)> K2Node_CreateDelegate_OutputDelegate; // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class ASurvivalPlayerState* Sender)> K2Node_CreateDelegate_OutputDelegate_1;      // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0024(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_1;              // 0x0034(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ASurvivalPlayerState*                   CallFunc_GetLocalSurvivalPlayerState_ReturnValue;  // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASurvivalPlayerState*                   K2Node_CustomEvent_Sender_1;                       // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bValue;                         // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASurvivalPlayerState*                   CallFunc_GetLocalSurvivalPlayerState_ReturnValue_1; // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASurvivalPlayerState*                   K2Node_CustomEvent_Sender;                         // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASurvivalPlayerState*                   CallFunc_GetLocalSurvivalPlayerState_ReturnValue_2; // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASurvivalPlayerState*                   CallFunc_GetLocalSurvivalPlayerState_ReturnValue_3; // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0088(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0098(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_1;             // 0x00AC(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_1;              // 0x00BC(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_2;             // 0x00D0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_2;              // 0x00E0(0x0014)()
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_2;              // 0x00F4(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MapResourceSurveyOverlay_C_ExecuteUbergraph_UI_MapResourceSurveyOverlay;

// Function UI_MapResourceSurveyOverlay.UI_MapResourceSurveyOverlay_C.Handle Visibility Changed
// 0x0010 (0x0010 - 0x0000)
struct UI_MapResourceSurveyOverlay_C_Handle_Visibility_Changed final
{
public:
	class ASurvivalPlayerState*                   Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          bValue;                                            // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MapResourceSurveyOverlay_C_Handle_Visibility_Changed;

// Function UI_MapResourceSurveyOverlay.UI_MapResourceSurveyOverlay_C.HandleOnRescan
// 0x0008 (0x0008 - 0x0000)
struct UI_MapResourceSurveyOverlay_C_HandleOnRescan final
{
public:
	class ASurvivalPlayerState*                   Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MapResourceSurveyOverlay_C_HandleOnRescan;

// Function UI_MapResourceSurveyOverlay.UI_MapResourceSurveyOverlay_C.UpdateHeatmapVisibility
// 0x0018 (0x0018 - 0x0000)
struct UI_MapResourceSurveyOverlay_C_UpdateHeatmapVisibility final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class ASurvivalPlayerState*                   CallFunc_GetLocalSurvivalPlayerState_ReturnValue;  // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsResourceSurveyVisible_ReturnValue;      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MapResourceSurveyOverlay_C_UpdateHeatmapVisibility;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
