#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MapResourceWaypoint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Maine_structs.hpp"
#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_MapResourceWaypoint.UI_MapResourceWaypoint_C
// 0x0030 (0x0400 - 0x03D0)
class UUI_MapResourceWaypoint_C final : public UMapResourceWaypointWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               Overlay_0;                                         // 0x03D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MarkerImage;                                       // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_0;                                     // 0x03E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ArrowRotationOverlay;                              // 0x03F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ArrowIcon;                                         // 0x03F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_MapResourceWaypoint(int32 EntryPoint);
	void OnLoaded_FFD1B5E64FDFCCE64B8ADD912EA9B15C(class UObject* Loaded);
	void RefreshVisuals();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_MapResourceWaypoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_MapResourceWaypoint_C")
	}
	static class UUI_MapResourceWaypoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_MapResourceWaypoint_C>();
	}
};
DUMPER7_ASSERTS_UUI_MapResourceWaypoint_C;

SDK_NAMESPACE_END
