#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MutationsGrid

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_MutationsGrid.UI_MutationsGrid_C.ExecuteUbergraph_UI_MutationsGrid
// 0x08E0 (0x08E0 - 0x0000)
struct UI_MutationsGrid_C_ExecuteUbergraph_UI_MutationsGrid final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0014(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_1;             // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_1;              // 0x0038(0x0014)()
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0050(0x00B0)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_1;                    // 0x0100(0x00B0)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_2;             // 0x01B0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_2;              // 0x01C0(0x0014)()
	uint8                                         Pad_1D4[0xC];                                      // 0x01D4(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_2;                    // 0x01E0(0x00B0)()
	struct FScrollBarStyle                        K2Node_MakeStruct_ScrollBarStyle;                  // 0x0290(0x0650)()
};
DUMPER7_ASSERTS_UI_MutationsGrid_C_ExecuteUbergraph_UI_MutationsGrid;

// Function UI_MutationsGrid.UI_MutationsGrid_C.SetScrollStyle
// 0x0008 (0x0008 - 0x0000)
struct UI_MutationsGrid_C_SetScrollStyle final
{
public:
	class UScrollBox*                             ScrollWidget;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_MutationsGrid_C_SetScrollStyle;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
