#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MapEntryBox

#include "Basic.hpp"

#include "UI_MapEntryBox_classes.hpp"
#include "UI_MapEntryBox_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_MapEntryBox.UI_MapEntryBox_C.BndEvt__UI_MapEntryBox_VisibleCheckbox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::BndEvt__UI_MapEntryBox_VisibleCheckbox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "BndEvt__UI_MapEntryBox_VisibleCheckbox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::UI_MapEntryBox_C_BndEvt__UI_MapEntryBox_VisibleCheckbox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_MapEntryBox_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_MapEntryBox_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.EventLargeFonts
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::EventLargeFonts(bool NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "EventLargeFonts");

	Params::UI_MapEntryBox_C_EventLargeFonts Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.ExecuteUbergraph_UI_MapEntryBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::ExecuteUbergraph_UI_MapEntryBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "ExecuteUbergraph_UI_MapEntryBox");

	Params::UI_MapEntryBox_C_ExecuteUbergraph_UI_MapEntryBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.GetEntryTypeName
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// EMapEntryType                           EntryType_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UUI_MapEntryBox_C::GetEntryTypeName(EMapEntryType EntryType_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "GetEntryTypeName");

	Params::UI_MapEntryBox_C_GetEntryTypeName Parms{};

	Parms.EntryType_0 = EntryType_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.HideMapEntry
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UUI_MapEntryBox_C::HideMapEntry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "HideMapEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.IsDestinationPTSInUse
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsInUse                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::IsDestinationPTSInUse(class UObject* Object, bool* IsInUse)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "IsDestinationPTSInUse");

	Params::UI_MapEntryBox_C_IsDestinationPTSInUse Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);

	if (IsInUse != nullptr)
		*IsInUse = Parms.IsInUse;
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.OnGlobalColorChange
// (Event, Protected, BlueprintEvent)

void UUI_MapEntryBox_C::OnGlobalColorChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "OnGlobalColorChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.OnLoaded_FFD1B5E64FDFCCE64B8ADD914CE93052
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::OnLoaded_FFD1B5E64FDFCCE64B8ADD914CE93052(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "OnLoaded_FFD1B5E64FDFCCE64B8ADD914CE93052");

	Params::UI_MapEntryBox_C_OnLoaded_FFD1B5E64FDFCCE64B8ADD914CE93052 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.OnMarkerEntryEnableStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::OnMarkerEntryEnableStateChanged(bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "OnMarkerEntryEnableStateChanged");

	Params::UI_MapEntryBox_C_OnMarkerEntryEnableStateChanged Parms{};

	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "PreConstruct");

	Params::UI_MapEntryBox_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.RefreshLockedCost
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPointOfInterestDataAsset*        POIData                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::RefreshLockedCost(class UPointOfInterestDataAsset* POIData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "RefreshLockedCost");

	Params::UI_MapEntryBox_C_RefreshLockedCost Parms{};

	Parms.POIData = POIData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.RefreshPOIControl
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_MapEntryBox_C::RefreshPOIControl()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "RefreshPOIControl");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.SetImageAsync
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UTexture>          NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UUI_MapEntryBox_C::SetImageAsync(TSoftObjectPtr<class UTexture> NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "SetImageAsync");

	Params::UI_MapEntryBox_C_SetImageAsync Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.SetLargeFont
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_MapEntryBox_C::SetLargeFont()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "SetLargeFont");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.SetMapEntry
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBaseMapEntryWidget*              MapEntry                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::SetMapEntry(class UBaseMapEntryWidget* MapEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "SetMapEntry");

	Params::UI_MapEntryBox_C_SetMapEntry Parms{};

	Parms.MapEntry = MapEntry;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.SetVisibilityVisuals
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    MapEntryEnabled                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::SetVisibilityVisuals(bool MapEntryEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "SetVisibilityVisuals");

	Params::UI_MapEntryBox_C_SetVisibilityVisuals Parms{};

	Parms.MapEntryEnabled = MapEntryEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.ShowMapEntry
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBaseMapEntryWidget*              MapEntry                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EMapEntryType                           EntryType_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bViaMouseHover                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Zoom                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 CursorPosition                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::ShowMapEntry(class UBaseMapEntryWidget* MapEntry, EMapEntryType EntryType_0, bool bViaMouseHover, float Zoom, const struct FVector2D& CursorPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "ShowMapEntry");

	Params::UI_MapEntryBox_C_ShowMapEntry Parms{};

	Parms.MapEntry = MapEntry;
	Parms.EntryType_0 = EntryType_0;
	Parms.bViaMouseHover = bViaMouseHover;
	Parms.Zoom = Zoom;
	Parms.CursorPosition = std::move(CursorPosition);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_MapEntryBox.UI_MapEntryBox_C.UpdatePosition
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Zoom                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_MapEntryBox_C::UpdatePosition(float Zoom)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_MapEntryBox_C", "UpdatePosition");

	Params::UI_MapEntryBox_C_UpdatePosition Parms{};

	Parms.Zoom = Zoom;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
