#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MakerModeControl

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Maine_classes.hpp"
#include "OEIText_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_MakerModeControl.UI_MakerModeControl_C
// 0x0068 (0x03E0 - 0x0378)
class UUI_MakerModeControl_C final : public UGameUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_HUDActionWidget_C*                  UI_HUDActionWidget;                                // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                OnlyFill;                                          // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_HoldFill_C*                         HoldFill;                                          // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizedTextBlock*                    ControlText_Loc;                                   // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Background;                                        // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBaseObjective*                         Objective;                                         // 0x03A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         ObjectiveIndex;                                    // 0x03B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseVerboseName;                                    // 0x03B4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NeverFade;                                         // 0x03B5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B6[0x2];                                      // 0x03B6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   ActionName;                                        // 0x03B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLocString                             LabelText;                                         // 0x03C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FLocString                             LocString;                                         // 0x03D0(0x0010)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_UI_MakerModeControl(int32 EntryPoint);
	struct FSlateColor GetBasicText();
	struct FLinearColor GetDisabledColor();
	void LargeTextEvent(bool NewValue);
	void OnGlobalColorChange();
	void PreConstruct(bool IsDesignTime);
	void SetLargeText();
	void SetLocString(const struct FLocString& LocString_0);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_MakerModeControl_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_MakerModeControl_C")
	}
	static class UUI_MakerModeControl_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_MakerModeControl_C>();
	}
};
DUMPER7_ASSERTS_UUI_MakerModeControl_C;

SDK_NAMESPACE_END
