#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_NotificationLog

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_NotificationLog.UI_NotificationLog_C
// 0x0038 (0x0388 - 0x0350)
class UUI_NotificationLog_C final : public UNotificationLogBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           LogList;                                           // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<double>                                TemporaryNotificationTimers;                       // 0x0360(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        TemporaryNotificationDisplayTime;                  // 0x0370(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRightAligned;                                    // 0x0378(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379[0x7];                                      // 0x0379(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Notification_C*                     ToggleNotification;                                // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ClearNotifications();
	void AddChatNotification(const struct FChatBoxMessage& ChatMessage, class UUI_Notification_C** Notification);
	void AddStashNotification(const struct FDataTableRowHandle& ItemRowHandle, int32 Count);
	void RemoveTemporaryNotificationReference(class UUI_Notification_C* NotificationIn, class UUI_Notification_C** Notification);
	void AddToggleNotification(const class FText& Message, const struct FColor& Color, class UTexture2D* MessageIcon);
	void AddGenericNotification(const class FText& Message, const struct FColor& Color, class UTexture2D* MessageIcon, class UUI_Notification_C** Notification);
	void InsertNotification(class UUI_Notification_C* Notification);
	void FindMatchingPickupNotification(const struct FDataTableRowHandle& Item, class UUI_Notification_C** Notification, int32* NotificationIndex);
	void AddPickupNotification(const struct FDataTableRowHandle& Item, int32 Count);
	void RemoveTemporaryNotification(int32 Index_0, class UUI_Notification_C** Notification);
	void CreateNewNotification(bool Temp, class UUI_Notification_C** NewNoticiation);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void AddGenericNotificationAsyncLoadIcon(const class FText& Message, const struct FColor& Color, TSoftObjectPtr<class UObject> MessageIcon);
	void ExecuteUbergraph_UI_NotificationLog(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_NotificationLog_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_NotificationLog_C")
	}
	static class UUI_NotificationLog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_NotificationLog_C>();
	}
};
DUMPER7_ASSERTS_UUI_NotificationLog_C;

SDK_NAMESPACE_END
