#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_PingLevel

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum UI_PingLevel.UI_PingLevel
// NumValues: 0x0006
enum class EUI_PingLevel : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator5                           = 4,
	UI_MAX                                   = 5,
};

SDK_NAMESPACE_END
