#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_RecipeNotification

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Maine_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_RecipeNotification.UI_RecipeNotification_C.EventLargeFonts
// 0x0001 (0x0001 - 0x0000)
struct UI_RecipeNotification_C_EventLargeFonts final
{
public:
	bool                                          NewValue;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_EventLargeFonts;

// Function UI_RecipeNotification.UI_RecipeNotification_C.ExecuteUbergraph_UI_RecipeNotification
// 0x0130 (0x0130 - 0x0000)
struct UI_RecipeNotification_C_ExecuteUbergraph_UI_RecipeNotification final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable;                              // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EBuildConfigationType                         CallFunc_GetBuildConfigationType_ReturnValue;      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDebugDelayAsyncLoading_ReturnValue;    // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x002C(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_1;              // 0x003C(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x004C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x005C(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_1;             // 0x0070(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_1;              // 0x0080(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_2;             // 0x0094(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_2;              // 0x00A4(0x0014)()
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor_3;             // 0x00B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor_3;              // 0x00C8(0x0014)()
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaineGameUserSettings*                 CallFunc_K2_GetMaineGameUserSettings_ReturnValue;  // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_NewValue;                       // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool NewValue)>                K2Node_CreateDelegate_OutputDelegate_1;            // 0x00EC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FD[0x3];                                       // 0x00FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UObject>                 K2Node_CustomEvent_Asset;                          // 0x0100(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_ExecuteUbergraph_UI_RecipeNotification;

// Function UI_RecipeNotification.UI_RecipeNotification_C.Get_ExclamitoryIcon_ColorAndOpacity_0
// 0x0034 (0x0034 - 0x0000)
struct UI_RecipeNotification_C_Get_ExclamitoryIcon_ColorAndOpacity_0 final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0020(0x0014)()
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_Get_ExclamitoryIcon_ColorAndOpacity_0;

// Function UI_RecipeNotification.UI_RecipeNotification_C.Get_NewItemBG_ColorAndOpacity_0
// 0x0034 (0x0034 - 0x0000)
struct UI_RecipeNotification_C_Get_NewItemBG_ColorAndOpacity_0 final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0020(0x0014)()
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_Get_NewItemBG_ColorAndOpacity_0;

// Function UI_RecipeNotification.UI_RecipeNotification_C.Get_NewItemBG_ColorAndOpacity_1
// 0x0034 (0x0034 - 0x0000)
struct UI_RecipeNotification_C_Get_NewItemBG_ColorAndOpacity_1 final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0020(0x0014)()
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_Get_NewItemBG_ColorAndOpacity_1;

// Function UI_RecipeNotification.UI_RecipeNotification_C.Get_PlayerNameBG_BrushColor_0
// 0x0034 (0x0034 - 0x0000)
struct UI_RecipeNotification_C_Get_PlayerNameBG_BrushColor_0 final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0020(0x0014)()
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_Get_PlayerNameBG_BrushColor_0;

// Function UI_RecipeNotification.UI_RecipeNotification_C.Get_Text_ColorAndOpacity_0
// 0x0038 (0x0038 - 0x0000)
struct UI_RecipeNotification_C_Get_Text_ColorAndOpacity_0 final
{
public:
	struct FSlateColor                            ReturnValue;                                       // 0x0000(0x0014)(Parm, OutParm, ReturnParm)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0024(0x0014)()
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_Get_Text_ColorAndOpacity_0;

// Function UI_RecipeNotification.UI_RecipeNotification_C.Get_Text_ShadowColorAndOpacity_0
// 0x0034 (0x0034 - 0x0000)
struct UI_RecipeNotification_C_Get_Text_ShadowColorAndOpacity_0 final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0020(0x0014)()
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_Get_Text_ShadowColorAndOpacity_0;

// Function UI_RecipeNotification.UI_RecipeNotification_C.GetAssociatedItemRow
// 0x0010 (0x0010 - 0x0000)
struct UI_RecipeNotification_C_GetAssociatedItemRow final
{
public:
	struct FDataTableRowHandle                    RowHandle;                                         // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_GetAssociatedItemRow;

// Function UI_RecipeNotification.UI_RecipeNotification_C.GetIcon
// 0x0FD0 (0x0FD0 - 0x0000)
struct UI_RecipeNotification_C_GetIcon final
{
public:
	class UObject*                                Image;                                             // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            IconBrush;                                         // 0x0010(0x00B0)(Parm, OutParm)
	TSoftObjectPtr<class UObject>                 SoftIcon;                                          // 0x00C0(0x0028)(Parm, OutParm, HasGetValueTypeHash)
	bool                                          CallFunc_IsBuildingRecipeFromDataTableRowHandle_ReturnValue; // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRecipeData                            CallFunc_GetDataTableRowFromName_OutRow;           // 0x00F0(0x00B8)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A9[0x7];                                      // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBuildingRecipeData                    CallFunc_GetDataTableRowFromName_OutRow_1;         // 0x01B0(0x0070)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_1;    // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_221[0x7];                                      // 0x0221(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBaseItemData                          CallFunc_GetDataTableRowFromName_OutRow_2;         // 0x0228(0x0A70)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_2;    // 0x0C98(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C99[0x7];                                      // 0x0C99(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBaseBuildingData                      CallFunc_GetDataTableRowFromName_OutRow_3;         // 0x0CA0(0x0320)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_3;    // 0x0FC0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_GetIcon;

// Function UI_RecipeNotification.UI_RecipeNotification_C.GetResourceColor
// 0x0034 (0x0034 - 0x0000)
struct UI_RecipeNotification_C_GetResourceColor final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0020(0x0014)()
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_GetResourceColor;

// Function UI_RecipeNotification.UI_RecipeNotification_C.OnLoaded_FFD1B5E64FDFCCE64B8ADD915F2C207B
// 0x0008 (0x0008 - 0x0000)
struct UI_RecipeNotification_C_OnLoaded_FFD1B5E64FDFCCE64B8ADD915F2C207B final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_OnLoaded_FFD1B5E64FDFCCE64B8ADD915F2C207B;

// Function UI_RecipeNotification.UI_RecipeNotification_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_RecipeNotification_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_PreConstruct;

// Function UI_RecipeNotification.UI_RecipeNotification_C.SetData
// 0x0F38 (0x0F38 - 0x0000)
struct UI_RecipeNotification_C_SetData final
{
public:
	struct FDataTableRowHandle                    RecipeAquired;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	class ASurvivalPlayerState*                   SurvivalPlayerState;                               // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FRecipeData                            CallFunc_GetDataTableRowFromName_OutRow;           // 0x0018(0x00B8)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBuildingRecipeData                    CallFunc_GetDataTableRowFromName_OutRow_1;         // 0x00D8(0x0070)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_1;    // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBaseBuildingData                      CallFunc_GetDataTableRowFromName_OutRow_2;         // 0x0150(0x0320)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_2;    // 0x0470(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_471[0x7];                                      // 0x0471(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBaseItemData                          CallFunc_GetDataTableRowFromName_OutRow_3;         // 0x0478(0x0A70)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_3;    // 0x0EE8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EE9[0x7];                                      // 0x0EE9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetLocalizedString_ReturnValue;           // 0x0EF0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetLocalizedString_ReturnValue_1;         // 0x0F00(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0F10(0x0010)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0F20(0x0010)()
	bool                                          CallFunc_IsBuildingRecipeFromDataTableRowHandle_ReturnValue; // 0x0F30(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_SetData;

// Function UI_RecipeNotification.UI_RecipeNotification_C.SetItemIconAsync
// 0x0028 (0x0028 - 0x0000)
struct UI_RecipeNotification_C_SetItemIconAsync final
{
public:
	TSoftObjectPtr<class UObject>                 Asset;                                             // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_SetItemIconAsync;

// Function UI_RecipeNotification.UI_RecipeNotification_C.SetLargeFont
// 0x01E8 (0x01E8 - 0x0000)
struct UI_RecipeNotification_C_SetLargeFont final
{
public:
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaineGameUserSettings*                 CallFunc_K2_GetMaineGameUserSettings_ReturnValue;  // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLargeText_ReturnValue;                 // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_MakeLiteralInt_ReturnValue_1;             // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0030(0x0060)(HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo_1;                 // 0x0090(0x0060)(HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue_2;             // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue_3;             // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_2;           // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_3;           // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo_2;                 // 0x0108(0x0060)(HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo_3;                 // 0x0168(0x0060)(HasGetValueTypeHash)
	class UMaineGameUserSettings*                 CallFunc_K2_GetMaineGameUserSettings_ReturnValue_1; // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLargeText_ReturnValue_1;               // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x01D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D2[0x2];                                      // 0x01D2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_MakeStruct_Size_ImplicitCast;               // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_Size_ImplicitCast_1;             // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_Size_ImplicitCast_2;             // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_Size_ImplicitCast_3;             // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_SetLargeFont;

// Function UI_RecipeNotification.UI_RecipeNotification_C.SetPlayerText
// 0x0020 (0x0020 - 0x0000)
struct UI_RecipeNotification_C_SetPlayerText final
{
public:
	class APlayerState*                           Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRecipeUnlock;                                    // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetTitleTextForPlayer_Title;              // 0x0010(0x0010)()
};
DUMPER7_ASSERTS_UI_RecipeNotification_C_SetPlayerText;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
