#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SpawnSelectorButton

#include "Basic.hpp"

#include "OEIText_structs.hpp"
#include "Maine_structs.hpp"
#include "Maine_classes.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_SpawnSelectorButton.UI_SpawnSelectorButton_C
// 0x0298 (0x0620 - 0x0388)
class UUI_SpawnSelectorButton_C final : public UGameButtonWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0388(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_HUDActionWidget_C*                  UI_HUDActionWidget;                                // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizedTextBlock*                    Text;                                              // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 OutlineSelector;                                   // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 CalloutIcon;                                       // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_NormalInner;                                // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BlurSelector;                                      // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BgSelector;                                        // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BevelSelector;                                     // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                BevelInside;                                       // 0x03D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       SelectAnim;                                        // 0x03D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       UnselectAnim;                                      // 0x03E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       HoverLineAnim;                                     // 0x03E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       SelectAnimImmediate;                               // 0x03F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UUI_NormalButton_C* Button, const struct FSpawnPointInfo& SpawnInfo)> OnNormalButtonClicked; // 0x03F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, BlueprintAssignable, BlueprintCallable)
	bool                                          Enabled;                                           // 0x0408(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Hovered;                                           // 0x0409(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40A[0x6];                                      // 0x040A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            HoveredBtn;                                        // 0x0410(0x00B0)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            UnhoveredBtn;                                      // 0x04C0(0x00B0)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FLocString                             LocString;                                         // 0x0570(0x0010)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowTutorialIcon;                                  // 0x0580(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_581[0x7];                                      // 0x0581(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSpawnPointInfo                        SpawnPointInfo;                                    // 0x0588(0x0070)(Edit, BlueprintVisible, ExposeOnSpawn)
	TMulticastInlineDelegate<void(const struct FSpawnPointInfo& SpawnInfo)> OnPreview;               // 0x05F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FSpawnPointInfo& SpawnInfo)> OnConfirm;               // 0x0608(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__Button_NormalInner_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__Button_NormalInner_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__Button_NormalInner_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__UI_NormalButton_Button_NormalInner_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
	void Construct();
	void Destruct();
	void EventLargeFonts(bool NewValue);
	void ExecuteUbergraph_UI_SpawnSelectorButton(int32 EntryPoint);
	void NormalButtonFocus();
	void NormalButtonHover();
	void NormalButtonUnfocus();
	void NormalButtonUnhover();
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnGameInputTypeChanged(const EGameInputType NewGameInputType);
	void OnGlobalColorChange();
	void OnInitialized();
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnUsingGamepadChanged(bool bOnUsingGamepadChanged);
	void PreConstruct(bool IsDesignTime);
	void SetDisabledStyle();
	void SetEnabledStyle();
	void SetHovered(bool Hovered_0);
	void SetIsValid(bool bEnabled);
	void SetLocalizedButtonText(const struct FLocString& LocalizedString);
	void SetTextSize();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_SpawnSelectorButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_SpawnSelectorButton_C")
	}
	static class UUI_SpawnSelectorButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_SpawnSelectorButton_C>();
	}
};
DUMPER7_ASSERTS_UUI_SpawnSelectorButton_C;

SDK_NAMESPACE_END
