#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_TabButton

#include "Basic.hpp"

#include "UI_TabButton_classes.hpp"
#include "UI_TabButton_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_TabButton.UI_TabButton_C.SetLargeFont
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_TabButton_C::SetLargeFont()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "SetLargeFont");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_TabButton.UI_TabButton_C.SetTootltip
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      ToolTip                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UUI_TabButton_C::SetTootltip(const class FText& ToolTip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "SetTootltip");

	Params::UI_TabButton_C_SetTootltip Parms{};

	Parms.ToolTip = std::move(ToolTip);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.GetItemTooltip
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUI_TabButton_C::GetItemTooltip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "GetItemTooltip");

	Params::UI_TabButton_C_GetItemTooltip Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_TabButton.UI_TabButton_C.Refresh
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_TabButton_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_TabButton.UI_TabButton_C.SetFontSize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  FontSize                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::SetFontSize(double FontSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "SetFontSize");

	Params::UI_TabButton_C_SetFontSize Parms{};

	Parms.FontSize = FontSize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.Get Checked State
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Checked                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::Get_Checked_State(bool* Checked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "Get Checked State");

	Params::UI_TabButton_C_Get_Checked_State Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Checked != nullptr)
		*Checked = Parms.Checked;
}


// Function UI_TabButton.UI_TabButton_C.SetString
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLocString&                LocString                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::SetString(const struct FLocString& LocString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "SetString");

	Params::UI_TabButton_C_SetString Parms{};

	Parms.LocString = std::move(LocString);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.OverrideString
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UUI_TabButton_C::OverrideString(const class FText& Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "OverrideString");

	Params::UI_TabButton_C_OverrideString Parms{};

	Parms.Name_0 = std::move(Name_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.SetIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Icon_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::SetIcon(class UTexture2D* Icon_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "SetIcon");

	Params::UI_TabButton_C_SetIcon Parms{};

	Parms.Icon_0 = Icon_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.GetVisibilityOSimg
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_TabButton_C::GetVisibilityOSimg()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "GetVisibilityOSimg");

	Params::UI_TabButton_C_GetVisibilityOSimg Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_TabButton.UI_TabButton_C.GetVisibilityIcon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_TabButton_C::GetVisibilityIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "GetVisibilityIcon");

	Params::UI_TabButton_C_GetVisibilityIcon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_TabButton.UI_TabButton_C.GetVisibilityText
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_TabButton_C::GetVisibilityText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "GetVisibilityText");

	Params::UI_TabButton_C_GetVisibilityText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_TabButton.UI_TabButton_C.GetAttentionColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_TabButton_C::GetAttentionColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "GetAttentionColor");

	Params::UI_TabButton_C_GetAttentionColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_TabButton.UI_TabButton_C.GetNuggetVisibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_TabButton_C::GetNuggetVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "GetNuggetVisibility");

	Params::UI_TabButton_C_GetNuggetVisibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_TabButton.UI_TabButton_C.GetSelectedColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_TabButton_C::GetSelectedColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "GetSelectedColor");

	Params::UI_TabButton_C_GetSelectedColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_TabButton.UI_TabButton_C.RefreshColors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_TabButton_C::RefreshColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "RefreshColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_TabButton.UI_TabButton_C.SetCheckedState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECheckBoxState                          InCheckedState                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::SetCheckedState(ECheckBoxState InCheckedState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "SetCheckedState");

	Params::UI_TabButton_C_SetCheckedState Parms{};

	Parms.InCheckedState = InCheckedState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.TabButtonUnhover
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                self2                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::TabButtonUnhover(class APlayerController* self2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "TabButtonUnhover");

	Params::UI_TabButton_C_TabButtonUnhover Parms{};

	Parms.self2 = self2;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.TabButtonHover
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                self2                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::TabButtonHover(class APlayerController* self2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "TabButtonHover");

	Params::UI_TabButton_C_TabButtonHover Parms{};

	Parms.self2 = self2;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.OnLoaded_FFD1B5E64FDFCCE64B8ADD9195191767
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::OnLoaded_FFD1B5E64FDFCCE64B8ADD9195191767(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "OnLoaded_FFD1B5E64FDFCCE64B8ADD9195191767");

	Params::UI_TabButton_C_OnLoaded_FFD1B5E64FDFCCE64B8ADD9195191767 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.BndEvt__Button_TabInner_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::BndEvt__Button_TabInner_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "BndEvt__Button_TabInner_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::UI_TabButton_C_BndEvt__Button_TabInner_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.OnGlobalColorChange
// (Event, Protected, BlueprintEvent)

void UUI_TabButton_C::OnGlobalColorChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "OnGlobalColorChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_TabButton.UI_TabButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "PreConstruct");

	Params::UI_TabButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_TabButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_TabButton.UI_TabButton_C.PlayNewItemAnim
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Play                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::PlayNewItemAnim(bool Play)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "PlayNewItemAnim");

	Params::UI_TabButton_C_PlayNewItemAnim Parms{};

	Parms.Play = Play;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.EventLargeFonts
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::EventLargeFonts(bool NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "EventLargeFonts");

	Params::UI_TabButton_C_EventLargeFonts Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_TabButton_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_TabButton.UI_TabButton_C.SetIconAsync
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UObject>           Icon_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UUI_TabButton_C::SetIconAsync(TSoftObjectPtr<class UObject> Icon_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "SetIconAsync");

	Params::UI_TabButton_C_SetIconAsync Parms{};

	Parms.Icon_0 = Icon_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.ExecuteUbergraph_UI_TabButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::ExecuteUbergraph_UI_TabButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "ExecuteUbergraph_UI_TabButton");

	Params::UI_TabButton_C_ExecuteUbergraph_UI_TabButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_TabButton.UI_TabButton_C.GetNarration
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// TArray<struct FNarrationChunk>&         Chunks                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bVerbose                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_TabButton_C::GetNarration(TArray<struct FNarrationChunk>& Chunks, bool bVerbose) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_TabButton_C", "GetNarration");

	Params::UI_TabButton_C_GetNarration Parms{};

	Parms.Chunks = std::move(Chunks);
	Parms.bVerbose = bVerbose;

	UObject::ProcessEvent(Func, &Parms);

	Chunks = std::move(Parms.Chunks);
}


SDK_NAMESPACE_END
