#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VITAL_Firefly_Tiredness

#include "Basic.hpp"

#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VITAL_Firefly_Tiredness.VITAL_Firefly_Tiredness_C
// 0x0000 (0x0090 - 0x0090)
class UVITAL_Firefly_Tiredness_C final : public UVitalStatFlyingTiredness
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VITAL_Firefly_Tiredness_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VITAL_Firefly_Tiredness_C")
	}
	static class UVITAL_Firefly_Tiredness_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVITAL_Firefly_Tiredness_C>();
	}
};
DUMPER7_ASSERTS_UVITAL_Firefly_Tiredness_C;

SDK_NAMESPACE_END
