#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WaveHeat

#include "Basic.hpp"

#include "OEIText_structs.hpp"
#include "Maine_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_WaveHeat.WBP_WaveHeat_C.ExecuteUbergraph_WBP_WaveHeat
// 0x0028 (0x0028 - 0x0000)
struct WBP_WaveHeat_C_ExecuteUbergraph_WBP_WaveHeat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColor_LinearColor;               // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            CallFunc_GetGlobalColor_SlateColor;                // 0x0014(0x0014)()
};
DUMPER7_ASSERTS_WBP_WaveHeat_C_ExecuteUbergraph_WBP_WaveHeat;

// Function WBP_WaveHeat.WBP_WaveHeat_C.GetWaveWarningString
// 0x0058 (0x0058 - 0x0000)
struct WBP_WaveHeat_C_GetWaveWarningString final
{
public:
	EWaveWarningLevel                             WarningLevel;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLocString                             WaveWarningLocString;                              // 0x0004(0x0010)(Parm, OutParm, NoDestructor, HasGetValueTypeHash)
	EWaveWarningLevel                             Temp_byte_Variable;                                // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLocString                             Temp_struct_Variable;                              // 0x0018(0x0010)(NoDestructor, HasGetValueTypeHash)
	struct FLocString                             Temp_struct_Variable_1;                            // 0x0028(0x0010)(NoDestructor, HasGetValueTypeHash)
	struct FLocString                             Temp_struct_Variable_2;                            // 0x0038(0x0010)(NoDestructor, HasGetValueTypeHash)
	struct FLocString                             K2Node_Select_Default;                             // 0x0048(0x0010)(NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_WaveHeat_C_GetWaveWarningString;

// Function WBP_WaveHeat.WBP_WaveHeat_C.SetWarningLevel
// 0x0128 (0x0128 - 0x0000)
struct WBP_WaveHeat_C_SetWarningLevel final
{
public:
	EWaveWarningLevel                             WaveWarningLevel;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CurrentProgress;                                   // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLocString                             CallFunc_MakeLocString_ReturnValue;                // 0x0008(0x0010)(NoDestructor, HasGetValueTypeHash)
	struct FLocString                             CallFunc_GetWaveWarningString_WaveWarningLocString; // 0x0018(0x0010)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetLocStringText_ReturnValue;             // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetLocalizedText_ReturnValue;             // 0x0038(0x0010)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0048(0x0010)()
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0068(0x0048)(HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_1;            // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x00C0(0x0048)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0108(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0118(0x0010)()
};
DUMPER7_ASSERTS_WBP_WaveHeat_C_SetWarningLevel;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
