#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Whistle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Maine_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Whistle.WBP_Whistle_C
// 0x0030 (0x03A8 - 0x0378)
class UWBP_Whistle_C final : public UGameUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 WhistleIcon;                                       // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_HUDActionWidget_C*                  UI_HUDActionWidget;                                // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MountIcon;                                         // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackgroundImage;                                   // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       PlayWhistleEffects;                                // 0x03A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void Destruct();
	void ExecuteUbergraph_WBP_Whistle(int32 EntryPoint);
	void OnGlobalColorChange();
	void OnPlayWhistlePetEffects();
	void Refresh_Mount_Icon_Color();
	void UpdateMountIcon(const struct FDataTableRowHandle& CreatureDataRowHandle);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Whistle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Whistle_C")
	}
	static class UWBP_Whistle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Whistle_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Whistle_C;

SDK_NAMESPACE_END
