#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RecipeListItem_PTS

#include "Basic.hpp"

#include "WBP_RecipeListItem_PTS_classes.hpp"
#include "WBP_RecipeListItem_PTS_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_RecipeListItem_PTS.WBP_RecipeListItem_PTS_C.FilterTextMatches
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const class FText&                      FilterText                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipeListItem_PTS_C::FilterTextMatches(const class FText& FilterText, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipeListItem_PTS_C", "FilterTextMatches");

	Params::WBP_RecipeListItem_PTS_C_FilterTextMatches Parms{};

	Parms.FilterText = std::move(FilterText);

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function WBP_RecipeListItem_PTS.WBP_RecipeListItem_PTS_C.IsDiscovered
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_RecipeListItem_PTS_C::IsDiscovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipeListItem_PTS_C", "IsDiscovered");

	Params::WBP_RecipeListItem_PTS_C_IsDiscovered Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_RecipeListItem_PTS.WBP_RecipeListItem_PTS_C.SetPOI
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPointOfInterestDataAsset*        POIData_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_RecipeListItem_PTS_C::SetPOI(class UPointOfInterestDataAsset* POIData_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecipeListItem_PTS_C", "SetPOI");

	Params::WBP_RecipeListItem_PTS_C_SetPOI Parms{};

	Parms.POIData_0 = POIData_0;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
