#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AnalysingRequirements

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Slate_structs.hpp"
#include "Maine_classes.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_AnalysingRequirements.WBP_AnalysingRequirements_C
// 0x0070 (0x03E8 - 0x0378)
class UWBP_AnalysingRequirements_C final : public UGameUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                RequirementsBorder;                                // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                             RequirementPanel;                                  // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizedTextBlock*                    IngredientsText;                                   // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AnalysedItemSlot_C*                Ingredient;                                        // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AnalysedItemSlot_C*                UI_RecipeItemSlot;                                 // 0x03A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxItemsPerRow;                                    // 0x03A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowTitleText;                                     // 0x03AC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3AD[0x3];                                      // 0x03AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FDataTableRowHandle& RecipeItem, class UWBP_AnalysedItemSlot_C* RecipeItemSlot)> HandleRecipeItemSelected; // 0x03B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FDataTableRowHandle& Recipe, class UWBP_AnalysedItemSlot_C* RecipeItemSlot)> HandleRecipeItemFocused; // 0x03C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FDataTableRowHandle& RecipeItem, class UWBP_AnalysedItemSlot_C* RecipeItemSlot)> HandleRecipeItemAltSelected; // 0x03D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         OverrideWidth;                                     // 0x03E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETextJustify                                  HeaderJustification;                               // 0x03E4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HideHeaderBG;                                      // 0x03E5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bForceLargeFont;                                   // 0x03E6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void Destruct();
	void EventLargeFonts(bool NewValue);
	void ExecuteUbergraph_WBP_AnalysingRequirements(int32 EntryPoint);
	void FocusOnRecipeRequirement(const struct FDataTableRowHandle& RecipeRequirement);
	void GetFocusedRecipeItem(struct FDataTableRowHandle* ItemRowHandle);
	void GetFocusedRecipeItemSlot(class UWBP_AnalysedItemSlot_C** ItemRowHandle);
	void GetRequiredResearch(const struct FDataTableRowHandle& Item, TArray<struct FDataTableRowHandle>* ToResearch);
	bool HandleKeyEventChord(const struct FInputChord& InChord);
	void HasItemEquipped(const struct FDataTableRowHandle& Item, bool* HasItem);
	void OnGlobalColorChange();
	void OnRequirementClicked(const struct FDataTableRowHandle& IngredientRowHandle, class UWBP_AnalysedItemSlot_C* RecipeItemSlot);
	void OnRequirementDoubleClicked(const struct FDataTableRowHandle& ItemRowHandle, class UWBP_AnalysedItemSlot_C* RecipeItemSlot);
	void OnRequirementFocused(const struct FDataTableRowHandle& ItemRowHandle, class UWBP_AnalysedItemSlot_C* RecipeItemSlot);
	void PreConstruct(bool IsDesignTime);
	void SetLargeFont();
	void UpdateItemRequirements(const struct FDataTableRowHandle& CraftingRecipe);
	void UpdateRequirementsListVersion(const struct FDataTableRowHandle& RecipeResult, TArray<struct FDataTableRowHandle>& Requirements);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_AnalysingRequirements_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_AnalysingRequirements_C")
	}
	static class UWBP_AnalysingRequirements_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AnalysingRequirements_C>();
	}
};
DUMPER7_ASSERTS_UWBP_AnalysingRequirements_C;

SDK_NAMESPACE_END
