#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MilestoneMapBrowser

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_MilestoneMapBrowser.WBP_MilestoneMapBrowser_C.GetMapList
// 0x0010 (0x0010 - 0x0000)
struct WBP_MilestoneMapBrowser_C_GetMapList final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_WBP_MilestoneMapBrowser_C_GetMapList;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
