#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PersonalMilkMolarButton

#include "Basic.hpp"

#include "WBP_PersonalMilkMolarButton_classes.hpp"
#include "WBP_PersonalMilkMolarButton_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_PersonalMilkMolarButton.WBP_PersonalMilkMolarButton_C.RefreshNewnessIcon
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_PersonalMilkMolarButton_C::RefreshNewnessIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PersonalMilkMolarButton_C", "RefreshNewnessIcon");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
