#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BuggyBuffingStatItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Maine_structs.hpp"
#include "Maine_classes.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BuggyBuffingStatItem.WBP_BuggyBuffingStatItem_C
// 0x0040 (0x03B8 - 0x0378)
class UWBP_BuggyBuffingStatItem_C final : public UGameUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_TierDescription_C*                  StatTier;                                          // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGameTextBlock*                         StatText;                                          // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                StatHeaderBorder;                                  // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizedTextBlock*                    StatHeader;                                        // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         StatBox;                                           // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                StatBorder;                                        // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          Is_Upgrade_Value;                                  // 0x03B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BuggyBuffingStatItem(int32 EntryPoint);
	void OnGlobalColorChange();
	void SetDetails(const struct FLocString& Name_0, double Value, EStatusEffectValueType ValueType, bool IsTier, bool IsUpgradeValue, bool ShouldShowStats);
	void UpdateStatTextColor();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BuggyBuffingStatItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BuggyBuffingStatItem_C")
	}
	static class UWBP_BuggyBuffingStatItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BuggyBuffingStatItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BuggyBuffingStatItem_C;

SDK_NAMESPACE_END
