#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PersonalUpgrades

#include "Basic.hpp"

#include "OEIOnlineSubsystemUtils_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_PersonalUpgrades.WBP_PersonalUpgrades_C.PurchaseUpgrade
// 0x0038 (0x0038 - 0x0000)
struct WBP_PersonalUpgrades_C_PurchaseUpgrade final
{
public:
	class ASurvivalPlayerState*                   CallFunc_GetLocalSurvivalPlayerState_ReturnValue;  // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDataTableRowHandle_NetCrc32           K2Node_MakeStruct_DataTableRowHandle_NetCrc32;     // 0x0010(0x0028)(NoDestructor)
};
DUMPER7_ASSERTS_WBP_PersonalUpgrades_C_PurchaseUpgrade;

// Function WBP_PersonalUpgrades.WBP_PersonalUpgrades_C.RefreshUI
// 0x0010 (0x0010 - 0x0000)
struct WBP_PersonalUpgrades_C_RefreshUI final
{
public:
	class ASurvivalPlayerState*                   CallFunc_GetLocalSurvivalPlayerState_ReturnValue;  // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetRemainingUpgradePoints_ReturnValue;    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_PersonalUpgrades_C_RefreshUI;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
