#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_KeyNotificationQueue

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "Maine_classes.hpp"
#include "KeyNotificationQueueItem_structs.hpp"
#include "KeyNotificationType_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_KeyNotificationQueue.WBP_KeyNotificationQueue_C
// 0x0090 (0x0408 - 0x0378)
class UWBP_KeyNotificationQueue_C final : public UGameUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         Queue;                                             // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         MaxVisibleNotifNumber;                             // 0x0388(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38C[0x4];                                      // 0x038C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FKeyNotificationQueueItem>      IconQueue;                                         // 0x0390(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FSlateColor                            SCABosAccentOneGlobalColor;                        // 0x03A0(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateColor                            AttentionGlobalColor;                              // 0x03B4(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateColor                            AugustaBgBannerDarkGlobalColor;                    // 0x03C8(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateColor                            GlobalBGGlobalColor;                               // 0x03DC(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateColor                            WhiteSlateColor;                                   // 0x03F0(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void Add_To_Queue(class UObject* Icon, const struct FSlateBrush& IconBrush, EKeyNotificationType NotifType, TSoftObjectPtr<class UObject> SoftIcon);
	void ClearQueue();
	void Construct();
	void DeQueue();
	void ExecuteUbergraph_WBP_KeyNotificationQueue(int32 EntryPoint);
	void GetBackgroundColor(EKeyNotificationType NotifType, struct FSlateColor* NewParam);
	void GetIconTint(EKeyNotificationType NotifType, struct FSlateColor* NewParam);
	void GetOpacity(int32 Index_0, double* DesiredOpacity);
	void OnQueueChanged();
	void PreConstruct(bool IsDesignTime);
	void Refresh_Queue();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_KeyNotificationQueue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_KeyNotificationQueue_C")
	}
	static class UWBP_KeyNotificationQueue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_KeyNotificationQueue_C>();
	}
};
DUMPER7_ASSERTS_UWBP_KeyNotificationQueue_C;

SDK_NAMESPACE_END
