(() => {
  "use strict";

  const TREES = {
    Amazon: ["Bow and Crossbow", "Passive and Magic", "Javelin and Spear"],
    Sorceress: ["Fire", "Lightning", "Cold"],
    Necromancer: ["Curses", "Poison and Bone", "Summoning"],
    Paladin: ["Combat Skills", "Offensive Auras", "Defensive Auras"],
    Barbarian: ["Combat Skills", "Combat Masteries", "Warcries"],
    Druid: ["Elemental", "Shape Shifting", "Summoning"],
    Assassin: ["Martial Arts", "Shadow Disciplines", "Traps"],
  };

  // Slot 0-29 = D2S skill bytes, in skills.txt ID order. Tree index matches in-game tabs.
  const BY_CLASS = {
    Amazon: [
      { name: "Magic Arrow", tree: 0 },
      { name: "Fire Arrow", tree: 0 },
      { name: "Inner Sight", tree: 1 },
      { name: "Critical Strike", tree: 1 },
      { name: "Jab", tree: 2 },
      { name: "Cold Arrow", tree: 0 },
      { name: "Multiple Shot", tree: 0 },
      { name: "Dodge", tree: 1 },
      { name: "Power Strike", tree: 2 },
      { name: "Poison Javelin", tree: 2 },
      { name: "Exploding Arrow", tree: 0 },
      { name: "Slow Movement", tree: 1 },
      { name: "Avoid", tree: 1 },
      { name: "Javelin and Spear Mastery", tree: 2 },
      { name: "Lightning Bolt", tree: 2 },
      { name: "Ice Arrow", tree: 0 },
      { name: "Guided Arrow", tree: 0 },
      { name: "Penetrate", tree: 1 },
      { name: "Charged Strike", tree: 2 },
      { name: "Plague Javelin", tree: 2 },
      { name: "Strafe", tree: 0 },
      { name: "Immolation Arrow", tree: 0 },
      { name: "Decoy", tree: 1 },
      { name: "Evade", tree: 1 },
      { name: "Fend", tree: 2 },
      { name: "Freezing Arrow", tree: 0 },
      { name: "Valkyrie", tree: 1 },
      { name: "Pierce", tree: 1 },
      { name: "Lightning Strike", tree: 2 },
      { name: "Lightning Fury", tree: 2 },
    ],
    Sorceress: [
      { name: "Fire Bolt", tree: 0 },
      { name: "Warmth", tree: 0 },
      { name: "Charged Bolt", tree: 1 },
      { name: "Ice Bolt", tree: 2 },
      { name: "Cold Enchant", tree: 2 },
      { name: "Inferno", tree: 0 },
      { name: "Static Field", tree: 1 },
      { name: "Telekinesis", tree: 1 },
      { name: "Frost Nova", tree: 2 },
      { name: "Ice Blast", tree: 2 },
      { name: "Blaze", tree: 0 },
      { name: "Fire Ball", tree: 0 },
      { name: "Nova", tree: 1 },
      { name: "Lightning", tree: 1 },
      { name: "Shiver Armor", tree: 2 },
      { name: "Fire Wall", tree: 0 },
      { name: "Enchant", tree: 0 },
      { name: "Chain Lightning", tree: 1 },
      { name: "Teleport", tree: 1 },
      { name: "Glacial Spike", tree: 2 },
      { name: "Meteor", tree: 0 },
      { name: "Thunder Storm", tree: 1 },
      { name: "Energy Shield", tree: 1 },
      { name: "Blizzard", tree: 2 },
      { name: "Chilling Armor", tree: 2 },
      { name: "Fire Mastery", tree: 0 },
      { name: "Hydra", tree: 0 },
      { name: "Lightning Mastery", tree: 1 },
      { name: "Frozen Orb", tree: 2 },
      { name: "Cold Mastery", tree: 2 },
    ],
    Necromancer: [
      { name: "Amplify Damage", tree: 0 },
      { name: "Teeth", tree: 1 },
      { name: "Bone Armor", tree: 1 },
      { name: "Skeleton Mastery", tree: 2 },
      { name: "Raise Skeleton", tree: 2 },
      { name: "Dim Vision", tree: 0 },
      { name: "Weaken", tree: 0 },
      { name: "Poison Dagger", tree: 1 },
      { name: "Corpse Explosion", tree: 1 },
      { name: "Clay Golem", tree: 2 },
      { name: "Iron Maiden", tree: 0 },
      { name: "Terror", tree: 0 },
      { name: "Bone Wall", tree: 1 },
      { name: "Golem Mastery", tree: 2 },
      { name: "Raise Skeletal Mage", tree: 2 },
      { name: "Confuse", tree: 0 },
      { name: "Life Tap", tree: 0 },
      { name: "Desecrate", tree: 1 },
      { name: "Bone Spear", tree: 1 },
      { name: "Blood Golem", tree: 2 },
      { name: "Attract", tree: 0 },
      { name: "Decrepify", tree: 0 },
      { name: "Bone Prison", tree: 1 },
      { name: "Raise Skeleton Archer", tree: 2 },
      { name: "Iron Golem", tree: 2 },
      { name: "Lower Resist", tree: 0 },
      { name: "Poison Nova", tree: 1 },
      { name: "Bone Spirit", tree: 1 },
      { name: "Fire Golem", tree: 2 },
      { name: "Revive", tree: 2 },
    ],
    Paladin: [
      { name: "Sacrifice", tree: 0 },
      { name: "Smite", tree: 0 },
      { name: "Might", tree: 1 },
      { name: "Prayer", tree: 2 },
      { name: "Resist Fire", tree: 2 },
      { name: "Holy Bolt", tree: 0 },
      { name: "Holy Fire", tree: 1 },
      { name: "Thorns", tree: 1 },
      { name: "Defiance", tree: 2 },
      { name: "Resist Cold", tree: 2 },
      { name: "Zeal", tree: 0 },
      { name: "Charge", tree: 0 },
      { name: "Blessed Aim", tree: 1 },
      { name: "Cleansing", tree: 2 },
      { name: "Resist Lightning", tree: 2 },
      { name: "Vengeance", tree: 0 },
      { name: "Blessed Hammer", tree: 0 },
      { name: "Concentration", tree: 1 },
      { name: "Holy Freeze", tree: 1 },
      { name: "Vigor", tree: 2 },
      { name: "Holy Sword", tree: 0 },
      { name: "Holy Shield", tree: 0 },
      { name: "Holy Shock", tree: 1 },
      { name: "Sanctuary", tree: 1 },
      { name: "Meditation", tree: 2 },
      { name: "Fist of the Heavens", tree: 0 },
      { name: "Fanaticism", tree: 1 },
      { name: "Conviction", tree: 1 },
      { name: "Redemption", tree: 2 },
      { name: "Salvation", tree: 2 },
    ],
    Barbarian: [
      { name: "Bash", tree: 0 },
      { name: "Sword Mastery", tree: 1 },
      { name: "General Mastery", tree: 1 },
      { name: "Mace Mastery", tree: 1 },
      { name: "Howl", tree: 2 },
      { name: "Find Potion", tree: 2 },
      { name: "Leap", tree: 0 },
      { name: "Double Swing", tree: 0 },
      { name: "Polearm and Spear Mastery", tree: 1 },
      { name: "Throwing Mastery", tree: 1 },
      { name: "Spear Mastery", tree: 1 },
      { name: "Taunt", tree: 2 },
      { name: "Shout", tree: 2 },
      { name: "Stun", tree: 0 },
      { name: "Double Throw", tree: 0 },
      { name: "Combat Reflexes", tree: 1 },
      { name: "Find Item", tree: 2 },
      { name: "Leap Attack", tree: 0 },
      { name: "Concentrate", tree: 0 },
      { name: "Iron Skin", tree: 1 },
      { name: "Battle Cry", tree: 2 },
      { name: "Frenzy", tree: 0 },
      { name: "Increased Speed", tree: 1 },
      { name: "Battle Orders", tree: 2 },
      { name: "Grim Ward", tree: 2 },
      { name: "Whirlwind", tree: 0 },
      { name: "Berserk", tree: 0 },
      { name: "Natural Resistance", tree: 1 },
      { name: "War Cry", tree: 2 },
      { name: "Battle Command", tree: 2 },
    ],
    Druid: [
      { name: "Raven", tree: 2 },
      { name: "Poison Creeper", tree: 2 },
      { name: "Werewolf", tree: 1 },
      { name: "Lycanthropy", tree: 1 },
      { name: "Firestorm", tree: 0 },
      { name: "Oak Sage", tree: 2 },
      { name: "Summon Spirit Wolf", tree: 2 },
      { name: "Werebear", tree: 1 },
      { name: "Molten Boulder", tree: 0 },
      { name: "Arctic Blast", tree: 0 },
      { name: "Carrion Vine", tree: 2 },
      { name: "Feral Rage", tree: 1 },
      { name: "Maul", tree: 1 },
      { name: "Fissure", tree: 0 },
      { name: "Cyclone Armor", tree: 0 },
      { name: "Heart of Wolverine", tree: 2 },
      { name: "Summon Dire Wolf", tree: 2 },
      { name: "Rabies", tree: 1 },
      { name: "Fire Claws", tree: 1 },
      { name: "Twister", tree: 0 },
      { name: "Solar Creeper", tree: 2 },
      { name: "Hunger", tree: 1 },
      { name: "Shock Wave", tree: 1 },
      { name: "Volcano", tree: 0 },
      { name: "Tornado", tree: 0 },
      { name: "Spirit of Barbs", tree: 2 },
      { name: "Summon Grizzly", tree: 2 },
      { name: "Fury", tree: 1 },
      { name: "Armageddon", tree: 0 },
      { name: "Hurricane", tree: 0 },
    ],
    Assassin: [
      { name: "Fire Blast", tree: 2 },
      { name: "Claw Mastery", tree: 1 },
      { name: "Psychic Hammer", tree: 1 },
      { name: "Tiger Strike", tree: 0 },
      { name: "Dragon Talon", tree: 0 },
      { name: "Shock Web", tree: 2 },
      { name: "Blade Sentinel", tree: 2 },
      { name: "Burst of Speed", tree: 1 },
      { name: "Fists of Fire", tree: 0 },
      { name: "Dragon Claw", tree: 0 },
      { name: "Charged Bolt Sentry", tree: 2 },
      { name: "Wake of Fire", tree: 2 },
      { name: "Weapon Block", tree: 1 },
      { name: "Cloak of Shadows", tree: 1 },
      { name: "Cobra Strike", tree: 0 },
      { name: "Blade Fury", tree: 2 },
      { name: "Fade", tree: 1 },
      { name: "Shadow Warrior", tree: 1 },
      { name: "Claws of Thunder", tree: 0 },
      { name: "Dragon Tail", tree: 0 },
      { name: "Chain Lightning Sentry", tree: 2 },
      { name: "Inferno Sentry", tree: 2 },
      { name: "Mind Blast", tree: 1 },
      { name: "Blades of Ice", tree: 0 },
      { name: "Dragon Flight", tree: 0 },
      { name: "Death Sentry", tree: 2 },
      { name: "Blade Shield", tree: 2 },
      { name: "Venom", tree: 1 },
      { name: "Shadow Master", tree: 1 },
      { name: "Phoenix Strike", tree: 0 },
    ],
  };

  const ALL = [{"i":0,"n":"Attack"},{"i":1,"n":"Kick"},{"i":2,"n":"Throw"},{"i":3,"n":"Unsummon"},{"i":4,"n":"Left Hand Throw"},{"i":5,"n":"Left Hand Swing"},{"i":6,"n":"Magic Arrow"},{"i":7,"n":"Fire Arrow"},{"i":8,"n":"Inner Sight"},{"i":9,"n":"Critical Strike"},{"i":10,"n":"Jab"},{"i":11,"n":"Cold Arrow"},{"i":12,"n":"Multiple Shot"},{"i":13,"n":"Dodge"},{"i":14,"n":"Power Strike"},{"i":15,"n":"Poison Javelin"},{"i":16,"n":"Exploding Arrow"},{"i":17,"n":"Slow Movement"},{"i":18,"n":"Avoid"},{"i":19,"n":"Javelin and Spear Mastery"},{"i":20,"n":"Lightning Bolt"},{"i":21,"n":"Ice Arrow"},{"i":22,"n":"Tornado Shot"},{"i":23,"n":"Penetrate"},{"i":24,"n":"Frostgale"},{"i":25,"n":"Plague Javelin"},{"i":26,"n":"Strafe"},{"i":27,"n":"Immolation Arrow"},{"i":28,"n":"Dopplezon"},{"i":29,"n":"Evade"},{"i":30,"n":"Fend"},{"i":31,"n":"Freezing Arrow"},{"i":32,"n":"Valkyrie"},{"i":33,"n":"Pierce"},{"i":34,"n":"Lightning Strike"},{"i":35,"n":"Lightning Fury"},{"i":36,"n":"Fire Bolt"},{"i":37,"n":"Warmth"},{"i":38,"n":"Charged Bolt"},{"i":39,"n":"Ice Bolt"},{"i":40,"n":"Cold Enchant"},{"i":41,"n":"Inferno"},{"i":42,"n":"Static Field"},{"i":43,"n":"Telekinesis"},{"i":44,"n":"Frost Nova"},{"i":45,"n":"Ice Blast"},{"i":46,"n":"Blaze"},{"i":47,"n":"Fire Ball"},{"i":48,"n":"Nova"},{"i":49,"n":"Lightning Fussilade"},{"i":50,"n":"Shiver Armor"},{"i":51,"n":"Fire Wall"},{"i":52,"n":"Enchant"},{"i":53,"n":"Chain Lightning"},{"i":54,"n":"Teleport"},{"i":55,"n":"Glacial Spike"},{"i":56,"n":"Meteor"},{"i":57,"n":"Thunder Storm"},{"i":58,"n":"Energy Shield"},{"i":59,"n":"Blizzard"},{"i":60,"n":"Chilling Armor"},{"i":61,"n":"Fire Mastery"},{"i":62,"n":"Hydra"},{"i":63,"n":"Lightning Mastery"},{"i":64,"n":"Frozen Orb"},{"i":65,"n":"Cold Mastery"},{"i":66,"n":"AmpDmg"},{"i":67,"n":"Teeth"},{"i":68,"n":"Bone Armor"},{"i":69,"n":"Skeleton Mastery"},{"i":70,"n":"Raise Skeleton"},{"i":71,"n":"Dim Vision"},{"i":72,"n":"Weaken"},{"i":73,"n":"Poison Dagger"},{"i":74,"n":"Corpse Explosion"},{"i":75,"n":"Clay Golem"},{"i":76,"n":"Iron Maiden"},{"i":77,"n":"Terror"},{"i":78,"n":"Bone Wall"},{"i":79,"n":"Golem Mastery"},{"i":80,"n":"Raise Skeletal Mage"},{"i":81,"n":"Confuse"},{"i":82,"n":"Life Tap"},{"i":83,"n":"Desecrate"},{"i":84,"n":"Shattered Marrow"},{"i":85,"n":"BloodGolem"},{"i":86,"n":"Attract"},{"i":87,"n":"Decrepify"},{"i":88,"n":"Bone Prison"},{"i":89,"n":"Raise Skeleton Archer"},{"i":90,"n":"IronGolem"},{"i":91,"n":"LowRes"},{"i":92,"n":"Poison Nova"},{"i":93,"n":"Soulrend"},{"i":94,"n":"FireGolem"},{"i":95,"n":"Revive"},{"i":96,"n":"Sacrifice"},{"i":97,"n":"Smite"},{"i":98,"n":"Might"},{"i":99,"n":"Prayer"},{"i":100,"n":"Resist Fire"},{"i":101,"n":"Holy Bolt"},{"i":102,"n":"Holy Fire"},{"i":103,"n":"Thorns"},{"i":104,"n":"Defiance"},{"i":105,"n":"Resist Cold"},{"i":106,"n":"Zeal"},{"i":107,"n":"Charge"},{"i":108,"n":"Blessed Aim"},{"i":109,"n":"Cleansing"},{"i":110,"n":"Resist Lightning"},{"i":111,"n":"Vengeance"},{"i":112,"n":"Blessed Hammer"},{"i":113,"n":"Concentration"},{"i":114,"n":"Holy Freeze"},{"i":115,"n":"Vigor"},{"i":116,"n":"Holy Sword"},{"i":117,"n":"Holy Shield"},{"i":118,"n":"Holy Shock"},{"i":119,"n":"Sanctuary"},{"i":120,"n":"Meditation"},{"i":121,"n":"Fist of the Heavens"},{"i":122,"n":"Fanaticism"},{"i":123,"n":"Conviction"},{"i":124,"n":"Redemption"},{"i":125,"n":"Salvation"},{"i":126,"n":"Bash"},{"i":127,"n":"Sword Mastery"},{"i":128,"n":"One Hand Mastery"},{"i":129,"n":"Mace Mastery"},{"i":130,"n":"Howl"},{"i":131,"n":"Find Potion"},{"i":132,"n":"Leap"},{"i":133,"n":"Double Swing"},{"i":134,"n":"Two Hand Mastery"},{"i":135,"n":"Throwing Mastery"},{"i":136,"n":"Spear Mastery"},{"i":137,"n":"Taunt"},{"i":138,"n":"Shout"},{"i":139,"n":"Perforate"},{"i":140,"n":"Double Throw"},{"i":141,"n":"Combat Reflexes"},{"i":142,"n":"Find Item"},{"i":143,"n":"Leap Attack"},{"i":144,"n":"Concentrate"},{"i":145,"n":"Iron Skin"},{"i":146,"n":"Battle Cry"},{"i":147,"n":"Frenzy"},{"i":148,"n":"Increased Speed"},{"i":149,"n":"Battle Orders"},{"i":150,"n":"Grim Ward"},{"i":151,"n":"Whirlwind"},{"i":152,"n":"Berserk"},{"i":153,"n":"Natural Resistance"},{"i":154,"n":"War Cry"},{"i":155,"n":"Battle Command"},{"i":156,"n":"Fire Hit"},{"i":157,"n":"UnHolyBolt"},{"i":158,"n":"SkeletonRaise"},{"i":159,"n":"MaggotEgg"},{"i":160,"n":"ShamanFire"},{"i":161,"n":"MagottUp"},{"i":162,"n":"MagottDown"},{"i":163,"n":"MagottLay"},{"i":164,"n":"AndrialSpray"},{"i":165,"n":"Jump"},{"i":166,"n":"Swarm Move"},{"i":167,"n":"Nest"},{"i":168,"n":"Quick Strike"},{"i":169,"n":"VampireFireball"},{"i":170,"n":"VampireFirewall"},{"i":171,"n":"VampireMeteor"},{"i":172,"n":"GargoyleTrap"},{"i":173,"n":"SpiderLay"},{"i":174,"n":"VampireHeal"},{"i":175,"n":"VampireRaise"},{"i":176,"n":"Submerge"},{"i":177,"n":"FetishAura"},{"i":178,"n":"FetishInferno"},{"i":179,"n":"ZakarumHeal"},{"i":180,"n":"Emerge"},{"i":181,"n":"Resurrect"},{"i":182,"n":"Bestow"},{"i":183,"n":"MissileSkill1"},{"i":184,"n":"MonTeleport"},{"i":185,"n":"PrimeLightning"},{"i":186,"n":"PrimeBolt"},{"i":187,"n":"PrimeBlaze"},{"i":188,"n":"PrimeFirewall"},{"i":189,"n":"PrimeSpike"},{"i":190,"n":"PrimeIceNova"},{"i":191,"n":"PrimePoisonball"},{"i":192,"n":"PrimePoisonNova"},{"i":193,"n":"DiabLight"},{"i":194,"n":"DiabCold"},{"i":195,"n":"DiabFire"},{"i":196,"n":"FingerMageSpider"},{"i":197,"n":"DiabWall"},{"i":198,"n":"DiabRun"},{"i":199,"n":"DiabPrison"},{"i":200,"n":"PoisonBallTrap"},{"i":201,"n":"AndyPoisonBolt"},{"i":202,"n":"HireableMissile"},{"i":203,"n":"DesertTurret"},{"i":204,"n":"ArcaneTower"},{"i":205,"n":"MonBlizzard"},{"i":206,"n":"Mosquito"},{"i":207,"n":"CursedBallTrapRight"},{"i":208,"n":"CursedBallTrapLeft"},{"i":209,"n":"MonFrozenArmor"},{"i":210,"n":"MonBoneArmor"},{"i":211,"n":"MonBoneSpirit"},{"i":212,"n":"MonCurseCast"},{"i":213,"n":"HellMeteor"},{"i":214,"n":"RegurgitatorEat"},{"i":215,"n":"MonFrenzy"},{"i":216,"n":"QueenDeath"},{"i":217,"n":"Scroll of Identify"},{"i":218,"n":"Book of Identify"},{"i":219,"n":"Scroll of Townportal"},{"i":220,"n":"Book of Townportal"},{"i":221,"n":"Raven"},{"i":222,"n":"Plague Poppy"},{"i":223,"n":"Wearwolf"},{"i":224,"n":"Shape Shifting"},{"i":225,"n":"Firestorm"},{"i":226,"n":"Oak Sage"},{"i":227,"n":"Summon Spirit Wolf"},{"i":228,"n":"Wearbear"},{"i":229,"n":"Molten Boulder"},{"i":230,"n":"Arctic Blast"},{"i":231,"n":"Cycle of Life"},{"i":232,"n":"Feral Rage"},{"i":233,"n":"Maul"},{"i":234,"n":"Eruption"},{"i":235,"n":"Cyclone Armor"},{"i":236,"n":"Heart of Wolverine"},{"i":237,"n":"Summon Fenris"},{"i":238,"n":"Rabies"},{"i":239,"n":"Fire Claws"},{"i":240,"n":"Twister"},{"i":241,"n":"Vines"},{"i":242,"n":"Hunger"},{"i":243,"n":"Shock Wave"},{"i":244,"n":"Volcano"},{"i":245,"n":"Tornado"},{"i":246,"n":"Spirit of Barbs"},{"i":247,"n":"Summon Grizzly"},{"i":248,"n":"Fury"},{"i":249,"n":"Armageddon"},{"i":250,"n":"Hurricane"},{"i":251,"n":"Fire Trauma"},{"i":252,"n":"Claw Mastery"},{"i":253,"n":"Psychic Hammer"},{"i":254,"n":"Tiger Strike"},{"i":255,"n":"Dragon Talon"},{"i":256,"n":"Shock Field"},{"i":257,"n":"Blade Sentinel"},{"i":258,"n":"Quickness"},{"i":259,"n":"Fists of Fire"},{"i":260,"n":"Dragon Claw"},{"i":261,"n":"Charged Bolt Sentry"},{"i":262,"n":"Wake of Fire Sentry"},{"i":263,"n":"Weapon Block"},{"i":264,"n":"Cloak of Shadows"},{"i":265,"n":"Cobra Strike"},{"i":266,"n":"Blade Fury"},{"i":267,"n":"Fade"},{"i":268,"n":"Shadow Warrior"},{"i":269,"n":"Claws of Thunder"},{"i":270,"n":"Dragon Tail"},{"i":271,"n":"Chain Lightning Sentry"},{"i":272,"n":"Inferno Sentry"},{"i":273,"n":"Mind Blast"},{"i":274,"n":"Blades of Ice"},{"i":275,"n":"Dragon Flight"},{"i":276,"n":"Death Sentry"},{"i":277,"n":"Blade Shield"},{"i":278,"n":"Venom"},{"i":279,"n":"Shadow Master"},{"i":280,"n":"Royal Strike"},{"i":281,"n":"Wake Of Destruction Sentry"},{"i":282,"n":"Imp Inferno"},{"i":283,"n":"Imp Fireball"},{"i":284,"n":"Baal Taunt"},{"i":285,"n":"Baal Corpse Explode"},{"i":286,"n":"Baal Monster Spawn"},{"i":287,"n":"Catapult Charged Ball"},{"i":288,"n":"Catapult Spike Ball"},{"i":289,"n":"Suck Blood"},{"i":290,"n":"Cry Help"},{"i":291,"n":"Healing Vortex"},{"i":292,"n":"Teleport 2"},{"i":293,"n":"Self-resurrect"},{"i":294,"n":"Vine Attack"},{"i":295,"n":"Overseer Whip"},{"i":296,"n":"Barbs Aura"},{"i":297,"n":"Wolverine Aura"},{"i":298,"n":"Oak Sage Aura"},{"i":299,"n":"Imp Fire Missile"},{"i":300,"n":"Impregnate"},{"i":301,"n":"Siege Beast Stomp"},{"i":302,"n":"MinionSpawner"},{"i":303,"n":"CatapultBlizzard"},{"i":304,"n":"CatapultPlague"},{"i":305,"n":"CatapultMeteor"},{"i":306,"n":"BoltSentry"},{"i":307,"n":"CorpseCycler"},{"i":308,"n":"DeathMaul"},{"i":309,"n":"Defense Curse"},{"i":310,"n":"Blood Mana"},{"i":311,"n":"mon inferno sentry"},{"i":312,"n":"mon death sentry"},{"i":313,"n":"Sentry Chain Lightning"},{"i":314,"n":"fenris rage"},{"i":315,"n":"Baal Tentacle"},{"i":316,"n":"Baal Nova"},{"i":317,"n":"Baal Inferno"},{"i":318,"n":"Baal Cold Missiles"},{"i":319,"n":"MegademonInferno"},{"i":320,"n":"EvilHutSpawner"},{"i":321,"n":"CountessFirewall"},{"i":322,"n":"ImpBolt"},{"i":323,"n":"Horror Arctic Blast"},{"i":324,"n":"death sentry ltng"},{"i":325,"n":"VineCycler"},{"i":326,"n":"BearSmite"},{"i":327,"n":"Resurrect2"},{"i":328,"n":"BloodLordFrenzy"},{"i":329,"n":"Baal Teleport"},{"i":330,"n":"Imp Teleport"},{"i":331,"n":"Baal Clone Teleport"},{"i":332,"n":"ZakarumLightning"},{"i":333,"n":"VampireMissile"},{"i":334,"n":"MephistoMissile"},{"i":335,"n":"DoomKnightMissile"},{"i":336,"n":"RogueMissile"},{"i":337,"n":"HydraMissile"},{"i":338,"n":"NecromageMissile"},{"i":339,"n":"MonBow"},{"i":340,"n":"MonFireArrow"},{"i":341,"n":"MonColdArrow"},{"i":342,"n":"MonExplodingArrow"},{"i":343,"n":"MonFreezingArrow"},{"i":344,"n":"MonPowerStrike"},{"i":345,"n":"SuccubusBolt"},{"i":346,"n":"MephFrostNova"},{"i":347,"n":"MonIceSpear"},{"i":348,"n":"ShamanIce"},{"i":349,"n":"Diablogeddon"},{"i":350,"n":"Delerium Change"},{"i":351,"n":"NihlathakCorpseExplosion"},{"i":352,"n":"SerpentCharge"},{"i":353,"n":"Trap Nova"},{"i":354,"n":"UnHolyBoltEx"},{"i":355,"n":"ShamanFireEx"},{"i":356,"n":"Imp Fire Missile Ex"},{"i":357,"n":"Blink"},{"i":358,"n":"proc_SplashDamage"},{"i":359,"n":"RoguePierce"},{"i":360,"n":"BattleOrdersCTA"},{"i":361,"n":"ExtraDrop"},{"i":362,"n":"BloodRavenImmo"},{"i":363,"n":"DollMeteor"},{"i":364,"n":"Divine Judgement"},{"i":365,"n":"Shattering Arrow"},{"i":366,"n":"Lightning Sentry"},{"i":367,"n":"Blood Warp"},{"i":368,"n":"Deep Wounds"},{"i":369,"n":"Ice Barrage"},{"i":370,"n":"Gust"},{"i":371,"n":"Holy Light"},{"i":372,"n":"amatemp2"},{"i":373,"n":"asatemp2"},{"i":374,"n":"CurMas"},{"i":375,"n":"Split Throw"},{"i":376,"n":"Combustion"},{"i":377,"n":"drutemp2"},{"i":378,"n":"Joust"},{"i":379,"n":"amatemp3"},{"i":380,"n":"Blade Dance"},{"i":381,"n":"Dark Pact"},{"i":382,"n":"bartemp3"},{"i":383,"n":"Lesser Hydra"},{"i":384,"n":"drutemp3"},{"i":385,"n":"Merc Fire Arrow"},{"i":386,"n":"Merc Cold Arrow"},{"i":387,"n":"Raven Splash"},{"i":388,"n":"Vampire Form"},{"i":389,"n":"Golem Splash"},{"i":390,"n":"KanemithBossBlaze"},{"i":391,"n":"Lesser Fade"},{"i":392,"n":"Sentry Lightning"},{"i":393,"n":"Skeleton Splash"},{"i":394,"n":"Force Move"},{"i":395,"n":"Immune Aura"},{"i":396,"n":"Immune Passive"},{"i":397,"n":"MegademonInfernoBoss"},{"i":398,"n":"MegademonBlazeBoss"},{"i":399,"n":"MegademonArmaBoss"},{"i":400,"n":"FingermageBossNova"},{"i":401,"n":"FingermageBossDiabWall"},{"i":402,"n":"FingermageBossShockWave"},{"i":403,"n":"CantorBossEruption"},{"i":404,"n":"CantorBossTornado"},{"i":405,"n":"UnravelerBossMultiShot"},{"i":406,"n":"UnravelerBossBuff"},{"i":407,"n":"UnravelerMinionBuff"},{"i":408,"n":"BaalMinionBossBerserk"},{"i":409,"n":"BaalMinionBossRabies"},{"i":410,"n":"BaalMinionBossCharge"},{"i":411,"n":"BaalMinionBossNova"},{"i":412,"n":"MonLeap"},{"i":413,"n":"MonJab"},{"i":414,"n":"MonSmite"},{"i":415,"n":"MonCharge"},{"i":416,"n":"MonHolyFreeze"},{"i":417,"n":"MonGlacialSpike"},{"i":418,"n":"MonFrostNova"},{"i":419,"n":"MonFireBall"},{"i":420,"n":"MonWeaken"},{"i":421,"n":"MonHydra"},{"i":422,"n":"MonLightning"},{"i":423,"n":"Fixed Siege Beast Stomp"},{"i":424,"n":"MonAmplifyDamage"},{"i":425,"n":"MonWhirlwind"},{"i":426,"n":"MonShout"},{"i":427,"n":"MonDecrepify"},{"i":428,"n":"MonChainLightning"},{"i":429,"n":"MonChillingArmor"},{"i":430,"n":"UberDiabloMeteor"},{"i":431,"n":"UberDiabloBoulder"},{"i":432,"n":"UberDiabWall"},{"i":433,"n":"UberDiabLight"},{"i":434,"n":"UberDiabCold"},{"i":435,"n":"UberDiabFire"},{"i":436,"n":"UberDiabSuperFire"},{"i":437,"n":"WispBossChainLightning"},{"i":438,"n":"WispMinionLightning"},{"i":439,"n":"WispTotemConviction"},{"i":440,"n":"MonLeapAttack"},{"i":441,"n":"FingerMageBossSpider"},{"i":442,"n":"AmpDmg Proc"},{"i":443,"n":"Weaken Proc"},{"i":444,"n":"Iron Maiden Proc"},{"i":445,"n":"Life Tap Proc"},{"i":446,"n":"Decrepify Proc"},{"i":447,"n":"LowRes Proc"},{"i":448,"n":"Iceboss Freezing Arrow"},{"i":449,"n":"Iceboss Blizzard"},{"i":450,"n":"Lightning Strike Cowboss"},{"i":451,"n":"Poison Nova Tomb Boss"},{"i":452,"n":"Power Strike Tomb Boss"},{"i":453,"n":"PoisonEggSpawn"},{"i":454,"n":"Hydra Throne Boss"},{"i":455,"n":"HurricaneTortureBoss"},{"i":456,"n":"A3 Mastery Fire"},{"i":457,"n":"A3 Mastery Cold"},{"i":458,"n":"A3 Mastery Ltng"},{"i":459,"n":"Merc Static Field"},{"i":460,"n":"A3 Merc Lightning"},{"i":461,"n":"A3 Merc Meteor"},{"i":462,"n":"A3 Merc Fire Ball"},{"i":463,"n":"A3 Merc Blizzard"},{"i":464,"n":"A3 Merc Ice Blast"},{"i":465,"n":"TraitorBossBlessedAim"},{"i":466,"n":"TraitorBossVigor"},{"i":467,"n":"TraitorBossConeJab"},{"i":468,"n":"TraitorBossStunSpear"},{"i":469,"n":"ArcherBossArrowRain"},{"i":470,"n":"ArcherBossBoomerShot"},{"i":471,"n":"ArcherBossCageShot"},{"i":472,"n":"Mon Conviction"},{"i":473,"n":"Mon Fanaticism"},{"i":474,"n":"Mon Holy Shock"},{"i":475,"n":"Mon Holy Freeze"},{"i":476,"n":"Mon Holy Fire"},{"i":477,"n":"Mon Might"},{"i":478,"n":"Mon Concentration"},{"i":479,"n":"Mon Vigor"},{"i":480,"n":"Baal Lowres"},{"i":481,"n":"Poison Dagger Spider Boss"},{"i":482,"n":"AndyPoisonBolt Spider Boss"},{"i":483,"n":"Tornado Arcane Boss"},{"i":484,"n":"Skeleton Archer Bow"},{"i":485,"n":"RathmaDeath"},{"i":486,"n":"NihlathakMapMobSpawn"},{"i":487,"n":"NihlathakMapDeath"},{"i":488,"n":"DoppleZonStrafe"},{"i":489,"n":"Valk Power Strike"},{"i":490,"n":"RathmaSummon"},{"i":491,"n":"RathmaBoneSpear"},{"i":492,"n":"RathmaTeethNova"},{"i":493,"n":"VoidBolt"},{"i":494,"n":"SummonVoidling"},{"i":495,"n":"IskatuHurricane"},{"i":496,"n":"RathmaPoisonOrb"},{"i":497,"n":"RathmaFissure"},{"i":498,"n":"RathmaOuterNova"},{"i":499,"n":"Horror Arctic Blast Boss"},{"i":500,"n":"Frost Nova Horror Boss"},{"i":501,"n":"Mon Holy Freeze Wide"},{"i":502,"n":"RathmaPacman"},{"i":503,"n":"Shock Wave Boss"},{"i":504,"n":"RathmaPrison"},{"i":505,"n":"RathmaColdMissiles"},{"i":506,"n":"Glacial Spike Spire"},{"i":507,"n":"Poison Nova Rathma"},{"i":508,"n":"Teeth Rathma"},{"i":509,"n":"UberTalicBlaze"},{"i":510,"n":"UberTalicWhirlwind"},{"i":511,"n":"UberTalicBash"},{"i":512,"n":"UberTalicMeteor"},{"i":513,"n":"Book of Unlimited Identify"},{"i":514,"n":"Book of Unlimited Townportal"},{"i":515,"n":"BruteFireSlam"},{"i":516,"n":"BruteMoltenBoulder"},{"i":517,"n":"BruteShockWave"},{"i":518,"n":"BruteVigor"},{"i":519,"n":"UberMadawcDoubleThrow"},{"i":520,"n":"UberMadawcCursedAxe"},{"i":521,"n":"UberMadawcOWAxe"},{"i":522,"n":"UberTalicSmite"},{"i":523,"n":"UberMadawcFakeBO"},{"i":524,"n":"UberMadawcLightningStorm"},{"i":525,"n":"Cyclone ArmorMon"},{"i":526,"n":"LeoricSummonNova"},{"i":527,"n":"SiegeBeastClusterbomb"},{"i":528,"n":"SiegeBeastFireNova"},{"i":529,"n":"SiegeBeastBuffNova"},{"i":530,"n":"SiegeBeastOrb"},{"i":531,"n":"Holy Fire Fire Golem"},{"i":532,"n":"Holy Freeze Korlic"},{"i":533,"n":"Leap Attack Korlic"},{"i":534,"n":"Holy Fire Sanctuaryboss"},{"i":535,"n":"Howl Monster"},{"i":536,"n":"Bone Spear Serpent"},{"i":537,"n":"Fire Ball Ashen Boss"},{"i":538,"n":"Fire Nova"},{"i":539,"n":"ZharBarrage"},{"i":540,"n":"ZharStrike"},{"i":541,"n":"ZharArmageddon"},{"i":542,"n":"ZharNovaOrb"},{"i":543,"n":"ZharCloak"},{"i":544,"n":"DemonPillar Fireball"},{"i":545,"n":"Merc Magic Arrow"},{"i":546,"n":"UberDiabRun"},{"i":547,"n":"ZharMiniBossMeteorBlizzard"},{"i":548,"n":"ZharMiniBossCombustion"},{"i":549,"n":"DemonPillar Lightning"},{"i":550,"n":"GuardianOfFateSummon"},{"i":551,"n":"A4 Mastery"},{"i":552,"n":"A4 AmpDmg"},{"i":553,"n":"WarlordMiniBoss1BaalFire"},{"i":554,"n":"Energy Shield SelfAura"},{"i":555,"n":"Chilling Armor SelfAura"},{"i":556,"n":"Quickness SelfAura"},{"i":557,"n":"Blade Shield SelfAura"},{"i":558,"n":"IskatuBlizzard"},{"i":559,"n":"ButcherAura"},{"i":560,"n":"IskatuMagicOrb"},{"i":561,"n":"RakanothStrike"},{"i":562,"n":"TorajanBossNest"},{"i":563,"n":"KanemithFirestorm"},{"i":564,"n":"KanemithShockWeb"},{"i":565,"n":"SharptoothUnholyOrb"},{"i":566,"n":"SharptoothChainPoison"},{"i":567,"n":"SharptoothArmageddon"},{"i":568,"n":"RadamentBossRoyalFire"},{"i":569,"n":"WispBossNova"},{"i":570,"n":"RadamentBossMeteor"},{"i":571,"n":"LucionNova"},{"i":572,"n":"LucionBoneWave"},{"i":573,"n":"LucionBlink"},{"i":574,"n":"LucionRoyalFire"},{"i":575,"n":"LucionDash"},{"i":576,"n":"LucionPunish"},{"i":577,"n":"EruptionDemonRoadBoss"},{"i":578,"n":"Tentacle"},{"i":579,"n":"LucionCharge"},{"i":580,"n":"LucionDeath1"},{"i":581,"n":"LucionDeath2"},{"i":582,"n":"LucionDeath3"},{"i":583,"n":"LucionDeath4"},{"i":584,"n":"MonSmiteLucion"},{"i":585,"n":"MonLowerRes"},{"i":586,"n":"HydraFireball"},{"i":587,"n":"SummonVoidlingUniqueMap"},{"i":588,"n":"Bone Spear Putrid Defiler"},{"i":589,"n":"SummonViperUniqueMap"},{"i":590,"n":"ChargedBoltImperialMiniBoss"},{"i":591,"n":"ImperialMiniBossBlast"},{"i":592,"n":"UberDiabSummon"},{"i":593,"n":"Armageddon SelfAura"},{"i":594,"n":"Shock Field Ureh Boss"},{"i":595,"n":"Fire Trauma Ureh Boss"},{"i":596,"n":"Thunder Storm SelfAura"},{"i":597,"n":"VolcanoInvaderDruid"},{"i":598,"n":"ArmageddonInvaderDruid"},{"i":599,"n":"Frozen Orb Light"},{"i":600,"n":"Charged Bolt Djinnboss"},{"i":601,"n":"DjinnBoss Poison Bolt"},{"i":602,"n":"UnHolyBolt DjinnBoss"},{"i":603,"n":"Reserved for PD27"},{"i":604,"n":"Reserved for PD28"},{"i":605,"n":"Reserved for PD29"},{"i":606,"n":"Reserved for PD210"},{"i":607,"n":"Reserved for PD211"},{"i":608,"n":"Reserved for PD212"},{"i":609,"n":"Reserved for PD213"},{"i":610,"n":"Reserved for PD214"},{"i":611,"n":"Reserved for PD215"},{"i":612,"n":"Reserved for PD216"},{"i":613,"n":"Reserved for PD217"},{"i":614,"n":"Reserved for PD218"},{"i":615,"n":"Reserved for PD219"},{"i":616,"n":"Reserved for PD220"},{"i":617,"n":"Reserved for PD221"},{"i":618,"n":"Reserved for PD222"},{"i":619,"n":"Reserved for PD223"},{"i":620,"n":"Reserved for PD224"},{"i":621,"n":"Reserved for PD225"},{"i":622,"n":"Reserved for PD226"},{"i":623,"n":"Reserved for PD227"},{"i":624,"n":"Reserved for PD228"},{"i":625,"n":"Reserved for PD229"},{"i":626,"n":"OriginalSin Aura"},{"i":627,"n":"Transcendent Mind"},{"i":628,"n":"Transcendent Mind Mag"},{"i":629,"n":"TemperedFlesh"},{"i":630,"n":"OneWithNothing"},{"i":631,"n":"EmpoweredSpirit"},{"i":632,"n":"Frailty"},{"i":633,"n":"Bone Spear"},{"i":634,"n":"Mjolner Aura"},{"i":635,"n":"The Squire Aura"},{"i":636,"n":"Reinforce"},{"i":637,"n":"CrushToDeadlyConvert"},{"i":638,"n":"Rimefall"},{"i":639,"n":"Headhunter Speed"},{"i":640,"n":"Headhunter Damage"},{"i":641,"n":"HorrorOfOpulenceImmArrow"},{"i":642,"n":"MagebloodRegen"},{"i":643,"n":"Mind over matter selfaura"},{"i":644,"n":"Unused"},{"i":645,"n":"Bone Spirit"},{"i":646,"n":"LazarusFireWallOrb"},{"i":647,"n":"LazarusBasicAttack"},{"i":648,"n":"LazarusSummon"},{"i":649,"n":"LazarusMinionSkill"},{"i":650,"n":"LazarusMinionFirewall"},{"i":651,"n":"HellforgedMetalGridAura"},{"i":652,"n":"Call of the brotherhood Aura"},{"i":653,"n":"Sealed Fate"},{"i":654,"n":"Time Dilation Aura"},{"i":655,"n":"Onslaught"},{"i":656,"n":"Gale Force"},{"i":657,"n":"Indigon Stacks"},{"i":658,"n":"Indigon Bonus"},{"i":659,"n":"Spartan's Rage"},{"i":660,"n":"Arcane Tornado Shot"},{"i":661,"n":"Colossal meteor"},{"i":662,"n":"Lazarus Clone Holy Freeze"},{"i":663,"n":"Headhunter Soul Absorb"},{"i":664,"n":"Fade selfaura"},{"i":665,"n":"Endurance Charge"},{"i":666,"n":"Blink Arrow"},{"i":667,"n":"Blood Mage Tier 4"},{"i":668,"n":"Time Warp"},{"i":669,"n":"Time Freeze"},{"i":670,"n":"Juggernaut Tier 4"},{"i":671,"n":"Arcane Surge"},{"i":672,"n":"Hierophant Tier 4"},{"i":673,"n":"Berserker Tier 3"},{"i":674,"n":"Mastermind of Discord"},{"i":675,"n":"Elementalist Tier 4"},{"i":676,"n":"Occultist Tier 4"},{"i":677,"n":"Guardian Tier 4"},{"i":678,"n":"Lich Tier 4"},{"i":679,"n":"Wither"},{"i":680,"n":"Master Toxicist"},{"i":681,"n":"Ferocious Roar"},{"i":682,"n":"Spirit Walker Tier 3"},{"i":683,"n":"Gale Force Deadeye"},{"i":684,"n":"Deadeye Tier 4"},{"i":685,"n":"Chieftain Explosion"},{"i":686,"n":"Chieftain Tier 3"},{"i":687,"n":"Profane Bloom"},{"i":688,"n":"Screams Armor"},{"i":689,"n":"Screams Regen"},{"i":690,"n":"Rathpith Aura"},{"i":691,"n":"Svalinn Aura"},{"i":692,"n":"Saboteur tier 3"},{"i":693,"n":"Mark of Fate aura"},{"i":694,"n":"The Taming Aura"}];

  function forClass(className) {
    return BY_CLASS[className] || BY_CLASS.Amazon;
  }

  function skillHay(s) {
    const n = String(s.n || "");
    let extra = "";
    if (/^UberDiab/i.test(n)) extra += " uber diablo spawn clone";
    else if (/^Diab/i.test(n)) extra += " diablo";
    else if (/^Uber/i.test(n)) extra += " uber";
    return (n + " " + s.i + extra).toLowerCase();
  }

  function skillName(id) {
    const n = Number(id);
    const hit = ALL.find((s) => s.i === n);
    return hit ? hit.n : "Skill " + n;
  }

  function searchSkills(query) {
    const q = String(query || "").trim().toLowerCase();
    if (!q) return ALL.slice();
    const tokens = q.split(/\s+/).filter(Boolean);
    const out = [];
    for (const s of ALL) {
      const hay = skillHay(s);
      if (tokens.every((t) => hay.includes(t) || String(s.i) === t)) out.push(s);
    }
    return out;
  }

  const api = { TREES, BY_CLASS, ALL, forClass, skillName, searchSkills, skillHay };
  if (typeof window !== "undefined") window.SoESkills = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})();
