(() => {
  "use strict";

  const TREES = {
    Amazon: ["Bow and Crossbow", "Passive and Magic", "Javelin and Spear"],
    Sorceress: ["Fire", "Lightning", "Cold"],
    Necromancer: ["Curses", "Poison and Bone", "Summoning"],
    Paladin: ["Combat Skills", "Offensive Auras", "Defensive Auras"],
    Barbarian: ["Combat Skills", "Combat Masteries", "Warcries"],
    Druid: ["Elemental", "Shape Shifting", "Summoning"],
    Assassin: ["Martial Arts", "Shadow Disciplines", "Traps"],
  };

  // Slot 0-29 = D2S skill bytes, in skills.txt ID order. Tree index matches in-game tabs.
  const BY_CLASS = {
    Amazon: [
      { name: "Magic Arrow", tree: 0 },
      { name: "Fire Arrow", tree: 0 },
      { name: "Inner Sight", tree: 1 },
      { name: "Critical Strike", tree: 1 },
      { name: "Jab", tree: 2 },
      { name: "Cold Arrow", tree: 0 },
      { name: "Multiple Shot", tree: 0 },
      { name: "Dodge", tree: 1 },
      { name: "Power Strike", tree: 2 },
      { name: "Poison Javelin", tree: 2 },
      { name: "Exploding Arrow", tree: 0 },
      { name: "Slow Movement", tree: 1 },
      { name: "Avoid", tree: 1 },
      { name: "Javelin and Spear Mastery", tree: 2 },
      { name: "Lightning Bolt", tree: 2 },
      { name: "Ice Arrow", tree: 0 },
      { name: "Guided Arrow", tree: 0 },
      { name: "Penetrate", tree: 1 },
      { name: "Charged Strike", tree: 2 },
      { name: "Plague Javelin", tree: 2 },
      { name: "Strafe", tree: 0 },
      { name: "Immolation Arrow", tree: 0 },
      { name: "Decoy", tree: 1 },
      { name: "Evade", tree: 1 },
      { name: "Fend", tree: 2 },
      { name: "Freezing Arrow", tree: 0 },
      { name: "Valkyrie", tree: 1 },
      { name: "Pierce", tree: 1 },
      { name: "Lightning Strike", tree: 2 },
      { name: "Lightning Fury", tree: 2 },
    ],
    Sorceress: [
      { name: "Fire Bolt", tree: 0 },
      { name: "Warmth", tree: 0 },
      { name: "Charged Bolt", tree: 1 },
      { name: "Ice Bolt", tree: 2 },
      { name: "Cold Enchant", tree: 2 },
      { name: "Inferno", tree: 0 },
      { name: "Static Field", tree: 1 },
      { name: "Telekinesis", tree: 1 },
      { name: "Frost Nova", tree: 2 },
      { name: "Ice Blast", tree: 2 },
      { name: "Blaze", tree: 0 },
      { name: "Fire Ball", tree: 0 },
      { name: "Nova", tree: 1 },
      { name: "Lightning", tree: 1 },
      { name: "Shiver Armor", tree: 2 },
      { name: "Fire Wall", tree: 0 },
      { name: "Enchant", tree: 0 },
      { name: "Chain Lightning", tree: 1 },
      { name: "Teleport", tree: 1 },
      { name: "Glacial Spike", tree: 2 },
      { name: "Meteor", tree: 0 },
      { name: "Thunder Storm", tree: 1 },
      { name: "Energy Shield", tree: 1 },
      { name: "Blizzard", tree: 2 },
      { name: "Chilling Armor", tree: 2 },
      { name: "Fire Mastery", tree: 0 },
      { name: "Hydra", tree: 0 },
      { name: "Lightning Mastery", tree: 1 },
      { name: "Frozen Orb", tree: 2 },
      { name: "Cold Mastery", tree: 2 },
    ],
    Necromancer: [
      { name: "Amplify Damage", tree: 0 },
      { name: "Teeth", tree: 1 },
      { name: "Bone Armor", tree: 1 },
      { name: "Skeleton Mastery", tree: 2 },
      { name: "Raise Skeleton", tree: 2 },
      { name: "Dim Vision", tree: 0 },
      { name: "Weaken", tree: 0 },
      { name: "Poison Dagger", tree: 1 },
      { name: "Corpse Explosion", tree: 1 },
      { name: "Clay Golem", tree: 2 },
      { name: "Iron Maiden", tree: 0 },
      { name: "Terror", tree: 0 },
      { name: "Bone Wall", tree: 1 },
      { name: "Golem Mastery", tree: 2 },
      { name: "Raise Skeletal Mage", tree: 2 },
      { name: "Confuse", tree: 0 },
      { name: "Life Tap", tree: 0 },
      { name: "Desecrate", tree: 1 },
      { name: "Bone Spear", tree: 1 },
      { name: "Blood Golem", tree: 2 },
      { name: "Attract", tree: 0 },
      { name: "Decrepify", tree: 0 },
      { name: "Bone Prison", tree: 1 },
      { name: "Raise Skeleton Archer", tree: 2 },
      { name: "Iron Golem", tree: 2 },
      { name: "Lower Resist", tree: 0 },
      { name: "Poison Nova", tree: 1 },
      { name: "Bone Spirit", tree: 1 },
      { name: "Fire Golem", tree: 2 },
      { name: "Revive", tree: 2 },
    ],
    Paladin: [
      { name: "Sacrifice", tree: 0 },
      { name: "Smite", tree: 0 },
      { name: "Might", tree: 1 },
      { name: "Prayer", tree: 2 },
      { name: "Resist Fire", tree: 2 },
      { name: "Holy Bolt", tree: 0 },
      { name: "Holy Fire", tree: 1 },
      { name: "Thorns", tree: 1 },
      { name: "Defiance", tree: 2 },
      { name: "Resist Cold", tree: 2 },
      { name: "Zeal", tree: 0 },
      { name: "Charge", tree: 0 },
      { name: "Blessed Aim", tree: 1 },
      { name: "Cleansing", tree: 2 },
      { name: "Resist Lightning", tree: 2 },
      { name: "Vengeance", tree: 0 },
      { name: "Blessed Hammer", tree: 0 },
      { name: "Concentration", tree: 1 },
      { name: "Holy Freeze", tree: 1 },
      { name: "Vigor", tree: 2 },
      { name: "Holy Sword", tree: 0 },
      { name: "Holy Shield", tree: 0 },
      { name: "Holy Shock", tree: 1 },
      { name: "Sanctuary", tree: 1 },
      { name: "Meditation", tree: 2 },
      { name: "Fist of the Heavens", tree: 0 },
      { name: "Fanaticism", tree: 1 },
      { name: "Conviction", tree: 1 },
      { name: "Redemption", tree: 2 },
      { name: "Salvation", tree: 2 },
    ],
    Barbarian: [
      { name: "Bash", tree: 0 },
      { name: "Sword Mastery", tree: 1 },
      { name: "General Mastery", tree: 1 },
      { name: "Mace Mastery", tree: 1 },
      { name: "Howl", tree: 2 },
      { name: "Find Potion", tree: 2 },
      { name: "Leap", tree: 0 },
      { name: "Double Swing", tree: 0 },
      { name: "Polearm and Spear Mastery", tree: 1 },
      { name: "Throwing Mastery", tree: 1 },
      { name: "Spear Mastery", tree: 1 },
      { name: "Taunt", tree: 2 },
      { name: "Shout", tree: 2 },
      { name: "Stun", tree: 0 },
      { name: "Double Throw", tree: 0 },
      { name: "Combat Reflexes", tree: 1 },
      { name: "Find Item", tree: 2 },
      { name: "Leap Attack", tree: 0 },
      { name: "Concentrate", tree: 0 },
      { name: "Iron Skin", tree: 1 },
      { name: "Battle Cry", tree: 2 },
      { name: "Frenzy", tree: 0 },
      { name: "Increased Speed", tree: 1 },
      { name: "Battle Orders", tree: 2 },
      { name: "Grim Ward", tree: 2 },
      { name: "Whirlwind", tree: 0 },
      { name: "Berserk", tree: 0 },
      { name: "Natural Resistance", tree: 1 },
      { name: "War Cry", tree: 2 },
      { name: "Battle Command", tree: 2 },
    ],
    Druid: [
      { name: "Raven", tree: 2 },
      { name: "Poison Creeper", tree: 2 },
      { name: "Werewolf", tree: 1 },
      { name: "Lycanthropy", tree: 1 },
      { name: "Firestorm", tree: 0 },
      { name: "Oak Sage", tree: 2 },
      { name: "Summon Spirit Wolf", tree: 2 },
      { name: "Werebear", tree: 1 },
      { name: "Molten Boulder", tree: 0 },
      { name: "Arctic Blast", tree: 0 },
      { name: "Carrion Vine", tree: 2 },
      { name: "Feral Rage", tree: 1 },
      { name: "Maul", tree: 1 },
      { name: "Fissure", tree: 0 },
      { name: "Cyclone Armor", tree: 0 },
      { name: "Heart of Wolverine", tree: 2 },
      { name: "Summon Dire Wolf", tree: 2 },
      { name: "Rabies", tree: 1 },
      { name: "Fire Claws", tree: 1 },
      { name: "Twister", tree: 0 },
      { name: "Solar Creeper", tree: 2 },
      { name: "Hunger", tree: 1 },
      { name: "Shock Wave", tree: 1 },
      { name: "Volcano", tree: 0 },
      { name: "Tornado", tree: 0 },
      { name: "Spirit of Barbs", tree: 2 },
      { name: "Summon Grizzly", tree: 2 },
      { name: "Fury", tree: 1 },
      { name: "Armageddon", tree: 0 },
      { name: "Hurricane", tree: 0 },
    ],
    Assassin: [
      { name: "Fire Blast", tree: 2 },
      { name: "Claw Mastery", tree: 1 },
      { name: "Psychic Hammer", tree: 1 },
      { name: "Tiger Strike", tree: 0 },
      { name: "Dragon Talon", tree: 0 },
      { name: "Shock Web", tree: 2 },
      { name: "Blade Sentinel", tree: 2 },
      { name: "Burst of Speed", tree: 1 },
      { name: "Fists of Fire", tree: 0 },
      { name: "Dragon Claw", tree: 0 },
      { name: "Charged Bolt Sentry", tree: 2 },
      { name: "Wake of Fire", tree: 2 },
      { name: "Weapon Block", tree: 1 },
      { name: "Cloak of Shadows", tree: 1 },
      { name: "Cobra Strike", tree: 0 },
      { name: "Blade Fury", tree: 2 },
      { name: "Fade", tree: 1 },
      { name: "Shadow Warrior", tree: 1 },
      { name: "Claws of Thunder", tree: 0 },
      { name: "Dragon Tail", tree: 0 },
      { name: "Chain Lightning Sentry", tree: 2 },
      { name: "Inferno Sentry", tree: 2 },
      { name: "Mind Blast", tree: 1 },
      { name: "Blades of Ice", tree: 0 },
      { name: "Dragon Flight", tree: 0 },
      { name: "Death Sentry", tree: 2 },
      { name: "Blade Shield", tree: 2 },
      { name: "Venom", tree: 1 },
      { name: "Shadow Master", tree: 1 },
      { name: "Phoenix Strike", tree: 0 },
    ],
  };

  function forClass(className) {
    return BY_CLASS[className] || BY_CLASS.Amazon;
  }

  const api = { TREES, BY_CLASS, forClass };
  if (typeof window !== "undefined") window.SoESkills = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})();
